(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const number=(id)=>{const el=document.getElementById(id);if(!el||String(el.value).trim()==='')return null;const v=Number(el.value);return Number.isFinite(v)?v:null};
const set=(id,text)=>{const el=document.getElementById(id);if(el)el.textContent=text};
const fmt=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
function announce(text){const el=$('#live');if(el)el.textContent=text}
function wireLabels(){let seq=0;$$('.field').forEach(field=>{const label=$('label',field),control=$('input,select,textarea',field);if(!label||!control)return;if(!control.id)control.id=`measure-field-auto-${++seq}`;if(!label.htmlFor)label.htmlFor=control.id});const table=$('#serial-tracker table');if(table){const headers=$$('thead th',table).map(th=>(th.textContent||'').trim());$$('tbody tr',table).forEach(row=>{const visit=($('td:first-child',row)?.textContent||'زيارة').trim();$$('input,select,textarea',row).forEach(control=>{if(control.id||control.hasAttribute('aria-label')||control.hasAttribute('aria-labelledby'))return;const cell=control.closest('td');const column=cell?headers[cell.cellIndex]||'حقل':'حقل';control.setAttribute('aria-label',`${visit} — ${column}`)})})}}
function wireExpandedLibraries(){const performance='/sectors/rehabilitation/measures/performance/',sppb='/sectors/rehabilitation/measures/sppb/',stay='/sectors/rehabilitation/measures/stay-independent/',pdi='/sectors/rehabilitation/measures/pdi/',bbs='/sectors/rehabilitation/measures/berg-balance-scale/',mas='/sectors/rehabilitation/measures/modified-ashworth-scale/',readiness='/sectors/rehabilitation/measures/arabic-readiness/',global='/assessments/global-measures/';const quick=$('.quick');for(const [href,label] of [[global,'البوابة العامة للمقاييس'],[performance,'اختبارات الأداء: 7 أوراق إضافية'],[sppb,'SPPB: البطارية الكاملة 0–12'],[stay,'Stay Independent: فحص السقوط 0–14'],[pdi,'PDI: العجز المرتبط بالألم 0–70'],[bbs,'BBS: مقياس بيرغ الكامل 0–56'],[mas,'MAS: التوتر/مقاومة الحركة 0،1،1+،2،3،4'],[readiness,'جاهزية النسخ العربية والحقوق']]){if(quick&&!$(`a[href="${href}"]`,quick)){const a=document.createElement('a');a.href=href;a.textContent=label;quick.appendChild(a)}}const anchor=$('#full-tools');if(anchor&&!document.getElementById('performance-wave-link')){const box=document.createElement('div');box.id='performance-wave-link';box.className='notice';box.innerHTML='<h3>مكتبة الأدوات العملية الموسعة</h3><p>أوراق أداء، SPPB، Stay Independent، PDI، BBS الكامل، وMAS لكل عضلة/مفصل دون مجموع زائف.</p><p><a class="button primary" href="'+performance+'">اختبارات الأداء</a> <a class="button" href="'+sppb+'">SPPB</a> <a class="button" href="'+stay+'">Stay Independent</a> <a class="button" href="'+pdi+'">PDI</a> <a class="button" href="'+bbs+'">BBS</a> <a class="button" href="'+mas+'">MAS</a> <a class="button" href="'+readiness+'">جاهزية العربية</a> <a class="button" href="'+global+'">البوابة العامة</a></p>';anchor.insertAdjacentElement('afterend',box)}}
function calc10m(){const recordedDistance=number('walk-distance');const distance=recordedDistance!==null&&recordedDistance>0?recordedDistance:10;const t1=number('walk-t1'),t2=number('walk-t2');const vals=[t1,t2].filter(v=>v!==null&&v>0);if(!vals.length){set('walk-result','—');return}const mean=vals.reduce((a,b)=>a+b,0)/vals.length;set('walk-result',`${fmt(distance/mean,2)} م/ث · متوسط الزمن ${fmt(mean,2)} ث`)}
function calcPSFS(){const vals=$$('.psfs-score').map(el=>String(el.value).trim()===''?null:Number(el.value)).filter(v=>v!==null&&Number.isFinite(v));if(!vals.length){set('psfs-result','—');return}set('psfs-result',`${fmt(vals.reduce((a,b)=>a+b,0)/vals.length,2)} / 10 (${vals.length} أنشطة)`)}
function calcNPRS(){const vals=[number('pain-now'),number('pain-best'),number('pain-worst'),number('pain-average')].filter(v=>v!==null);set('nprs-result',vals.length?`المتوسط المسجل: ${fmt(vals.reduce((a,b)=>a+b,0)/vals.length,1)} / 10`:'—')}
function calcTUG(){const vals=[number('tug-t1'),number('tug-t2')].filter(v=>v!==null&&v>0);if(!vals.length){set('tug-result','—');return}set('tug-result',`أفضل زمن ${fmt(Math.min(...vals),2)} ث · المتوسط ${fmt(vals.reduce((a,b)=>a+b,0)/vals.length,2)} ث`)}
function calcFTSST(){const t=number('fts-time');set('fts-result',t!==null&&t>0?`${fmt(t,2)} ثانية`:'—')}
function calcChair(){const reps=number('chair-reps');set('chair-result',reps!==null?`${Math.max(0,Math.floor(reps))} وقوف صحيح خلال 30 ثانية`:'—')}
function calcBalance(){const vals=['side','semi','tandem','single'].map(k=>number(`bal-${k}`)).filter(v=>v!==null);if(!vals.length){set('balance-result','—');return}set('balance-result',`${vals.filter(v=>v>=10).length}/${vals.length} وضعيات مسجلة بلغت 10 ثوانٍ · أقل زمن ${fmt(Math.min(...vals),1)} ث`)}
function recalc(){calcTUG();calcChair();calcBalance();calc10m();calcFTSST();calcNPRS();calcPSFS()}
wireLabels();wireExpandedLibraries();$$('input,select,textarea').forEach(el=>{el.addEventListener('input',recalc);el.addEventListener('change',recalc)});$$('.nprs-choice').forEach(btn=>btn.addEventListener('click',()=>{const target=document.getElementById(btn.dataset.target);if(target){target.value=btn.dataset.value;$$(`.nprs-choice[data-target="${btn.dataset.target}"]`).forEach(x=>x.setAttribute('aria-pressed',String(x===btn)));recalc()}}));$$('[data-print]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.print;$$('.measure').forEach(x=>x.classList.toggle('print-target',x.id===id));window.print();setTimeout(()=>$$('.measure').forEach(x=>x.classList.remove('print-target')),200)}));$$('[data-clear]').forEach(btn=>btn.addEventListener('click',()=>{const root=document.getElementById(btn.dataset.clear);if(!root)return;$$('input,textarea,select',root).forEach(el=>{if(el.tagName==='SELECT')el.selectedIndex=0;else if(el.type==='checkbox'||el.type==='radio')el.checked=false;else el.value=''});$$('[aria-pressed="true"]',root).forEach(el=>el.setAttribute('aria-pressed','false'));recalc();announce('تم مسح بيانات الورقة محليًا.')}));const search=$('#measure-search'),filter=$('#rights-filter');function filterCards(){const q=(search?.value||'').trim().toLowerCase(),f=filter?.value||'all';$$('[data-catalog-card]').forEach(card=>{const text=(card.textContent||'').toLowerCase();card.hidden=!((!q||text.includes(q))&&(f==='all'||card.dataset.status===f))})}search?.addEventListener('input',filterCards);filter?.addEventListener('change',filterCards);recalc();
})();