(() => {
'use strict';
const IDENTITY_API='https://pterminology-specialist-accounts.pterminology-826ac349.workers.dev';
const CORE_API='https://pterminology-specialists.pterminology-826ac349.workers.dev';
const TURNSTILE_SITE_KEY='0x4AAAAAAD_r2o__Ao1RmBTO';
const SESSION_KEYS=['ptIdentitySessionV6','ptAdminIdentityV6','ptSpecialistAccountSessionV5','ptSpecialistSessionV5','ptSpecialistSession','ptAdminSessionV4'];
const $=id=>document.getElementById(id);
const status=(message,type='loading')=>{const box=$('recover-status');box.textContent=message;box.dataset.state=type;box.focus?.();};
function extractToken(raw){try{const data=JSON.parse(raw||'null');return data?.token||data?.sessionToken||data?.accessToken||'';}catch(_){return '';}}
async function remoteRevoke(token,base){if(!token)return;try{await fetch(`${base}/v1/auth/logout`,{method:'POST',headers:{accept:'application/json','content-type':'application/json;charset=UTF-8','x-requested-with':'pterminology-recovery-v7',authorization:`Bearer ${token}`},body:'{}',cache:'no-store',credentials:'omit',redirect:'error',referrerPolicy:'no-referrer'});}catch(_){} }
async function clearSessions(){const tokens=[];for(const key of SESSION_KEYS){const value=sessionStorage.getItem(key);const token=extractToken(value);if(token)tokens.push(token);sessionStorage.removeItem(key);}for(let i=sessionStorage.length-1;i>=0;i--){const key=sessionStorage.key(i)||'';if(/^pt(?:Identity|Admin|Specialist).*Session/i.test(key)){const token=extractToken(sessionStorage.getItem(key));if(token)tokens.push(token);sessionStorage.removeItem(key);}}
await Promise.allSettled(tokens.flatMap(token=>[remoteRevoke(token,IDENTITY_API),remoteRevoke(token,CORE_API)]));$('session-result').textContent='تم حذف الجلسة المحلية القديمة من هذه النافذة. يمكنك الآن طلب رابط جديد أو العودة لتسجيل الدخول.';status('تم تسجيل الخروج محليًا وتنظيف الجلسة القديمة.','success');}
function initTurnstile(){const render=()=>{if(!window.turnstile)return;const target=$('recover-turnstile');if(target&&!target.dataset.rendered){window.turnstile.render(target,{sitekey:TURNSTILE_SITE_KEY,theme:'light',language:'ar',action:'password_reset'});target.dataset.rendered='true';}};if(window.turnstile)render();else{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.defer=true;script.onload=render;document.head.append(script);}}
function turnstileToken(){return $('recover-turnstile')?.querySelector('[name="cf-turnstile-response"]')?.value||'';}
async function postReset(base,payload){const response=await fetch(`${base}/v1/auth/password/request`,{method:'POST',headers:{accept:'application/json','content-type':'application/json;charset=UTF-8','x-requested-with':'pterminology-recovery-v7'},body:JSON.stringify(payload),cache:'no-store',credentials:'omit',redirect:'error',referrerPolicy:'no-referrer'});const data=await response.json().catch(()=>({}));return {response,data};}
async function submit(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const token=turnstileToken();if(!token){status('أكمل التحقق من الاستخدام البشري.','error');return;}const button=$('recover-submit');button.disabled=true;status('جارٍ إرسال رابط إعادة التعيين…');const payload={email:$('recover-email').value.trim(),turnstileToken:token};try{let result=await postReset(IDENTITY_API,payload);if(result.response.status===404)result=await postReset(CORE_API,payload);if(!result.response.ok)throw new Error(result.data.message||`تعذر إرسال الرابط (${result.response.status}).`);status(result.data.message||'تم قبول الطلب. افحص البريد خلال دقائق.','success');form.reset();$('recover-email').value='pterminology@gmail.com';try{window.turnstile?.reset?.();}catch(_){}}catch(error){status(error.message||'تعذر إرسال رابط إعادة التعيين.','error');try{window.turnstile?.reset?.();}catch(_){}}finally{button.disabled=false;}}
async function init(){await clearSessions();initTurnstile();$('recover-form').addEventListener('submit',submit);}
init();
})();
