from __future__ import annotations
import json,unittest,xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PAGE=ROOT/'sectors'/'rehabilitation'/'measures'/'action-research-arm-test'/'index.html';JS=PAGE.with_name('arat.js');REG=ROOT/'content'/'global-measures-v1'/'action-research-arm-test.json';CAT=ROOT/'content'/'global-measures-v1'/'catalog.json';AUDIT=ROOT/'content'/'global-measures-v1'/'rmd-eprovide-rights-audit.json';LIB=ROOT/'sectors'/'rehabilitation'/'measures'/'app.js';SITEMAP=ROOT/'sitemap-rehabilitation-measures.xml';GATE=ROOT/'assessments'/'global-measures'/'index.html';WORK=ROOT/'assessments'/'global-measures'/'workspace'/'index.html';FINDER=ROOT/'assessments'/'global-measures'/'tool-finder'/'index.html';PACKETS=ROOT/'assessments'/'global-measures'/'print-packets'/'index.html';UPPER=ROOT/'assessments'/'global-measures'/'print-packets'/'upper-limb-dexterity'/'index.html';NS={'s':'http://www.sitemaps.org/schemas/sitemap/0.9'}
class AratWave21Test(unittest.TestCase):
 @classmethod
 def setUpClass(cls):
  cls.html=PAGE.read_text(encoding='utf-8');cls.js=JS.read_text(encoding='utf-8');cls.reg=json.loads(REG.read_text(encoding='utf-8'));cls.catalog=json.loads(CAT.read_text(encoding='utf-8'));cls.audit=json.loads(AUDIT.read_text(encoding='utf-8'));cls.lib=LIB.read_text(encoding='utf-8');cls.xml=SITEMAP.read_text(encoding='utf-8');cls.gate=GATE.read_text(encoding='utf-8');cls.work=WORK.read_text(encoding='utf-8');cls.finder=FINDER.read_text(encoding='utf-8');cls.packets=PACKETS.read_text(encoding='utf-8');cls.upper=UPPER.read_text(encoding='utf-8')
 def test_19_items_four_subscales_and_57_max(self):
  self.assertEqual(self.reg['instrument']['items'],19);self.assertEqual(self.reg['instrument']['total_score_range'],[0,57]);self.assertEqual(self.reg['instrument']['subscales']['grasp']['max_score'],18);self.assertEqual(self.reg['instrument']['subscales']['grip']['max_score'],12);self.assertEqual(self.reg['instrument']['subscales']['pinch']['max_score'],18);self.assertEqual(self.reg['instrument']['subscales']['gross_movement']['max_score'],9);self.assertEqual(self.html.count('class="arat-score"'),19);self.assertIn("maxima={grasp:18,grip:12,pinch:18,gross:9}",self.js)
 def test_scoring_is_complete_only_and_ordinal(self):
  self.assertTrue(self.reg['scoring']['full_19_item_entry_required_for_rawafid_total']);self.assertTrue(self.reg['scoring']['lyle_hierarchical_decision_rules_documented_not_auto_applied']);self.assertTrue(self.reg['scoring']['do_not_treat_raw_score_as_interval_scale']);self.assertTrue(self.reg['scoring']['no_universal_diagnostic_cutoff']);self.assertIn('هذه الورقة لا تطبق الاختصار آليًا',self.html);self.assertIn("allComplete&&completed===19",self.js);self.assertIn('درجة رتبية',self.html)
 def test_one_arm_only_no_bilateral_total(self):
  self.assertTrue(self.reg['instrument']['arms_scored_separately']);self.assertFalse(self.reg['instrument']['aggregate_across_arms']);self.assertIn('كل ذراع مستقل',self.html);self.assertIn('لا تجمع 0–57 لليمين و0–57 لليسار',self.html);row=next(x for x in self.catalog['tools'] if x['id']=='arat');self.assertIn('no bilateral total',row['score'])
 def test_non_testable_and_safety_stop_suppress_total(self):
  self.assertTrue(self.reg['protocol_quality']['not_testable_or_safety_stop_suppresses_standard_total']);self.assertIn("if(status!=='testable')",self.js);self.assertIn("write('#arat-total','—')",self.js);self.assertIn('غير قابل للاختبار',self.html);self.assertIn('أوقف لأسباب السلامة/التعب',self.html);self.assertIn('عدم القابلية للاختبار ≠ صفر',self.html)
 def test_equipment_identity_and_2026_evidence(self):
  q=self.reg['protocol_quality'];self.assertTrue(q['record_kit_manufacturer_or_version']);self.assertTrue(q['same_equipment_and_setup_recommended_for_longitudinal_comparison']);self.assertTrue(q['alternative_equipment_should_not_be_assumed_equivalent_without_validation']);ev=self.reg['current_evidence']['alternative_kit_2026'];self.assertEqual(ev['doi'],'10.1371/journal.pone.0334199');self.assertEqual(ev['sample_n'],64);self.assertEqual(ev['intra_rater_icc_range'],[0.997,1.0]);self.assertEqual(ev['inter_rater_icc_range'],[0.979,0.999]);self.assertEqual(ev['convergent_spearman_fma_ue'],0.934);self.assertEqual(ev['convergent_spearman_bbt'],0.917);self.assertIn('ماذا أضاف دليل 2026؟',self.html);self.assertIn('العدة البديلة تحتاج تحققًا من التكافؤ',self.html)
 def test_rights_and_arabic_are_conservative(self):
  self.assertEqual(self.reg['rmd']['cost'],'Not Free');self.assertFalse(self.reg['rights']['instrument_public_domain_verified']);self.assertEqual(self.reg['rights']['rawafid_decision'],'operational-sheet-only');self.assertFalse(self.reg['arabic']['validated_or_authorized_arabic_form_verified']);self.assertFalse(self.reg['arabic']['claim_official_translation']);row=next(x for x in self.audit['current_library'] if x['id']=='arat');self.assertEqual(row['decision'],'operational-sheet-only');self.assertEqual(row['rmd_cost'],'Not Free');self.assertIn('equipment cost',row['rmd_cost_description'].lower());self.assertIn('لا تعيد نشر دليل بائع',self.html)
 def test_local_only_privacy(self):
  self.assertNotIn('fetch(',self.js);self.assertNotIn('localStorage',self.js);self.assertNotIn('sessionStorage',self.js);self.assertFalse(self.reg['instrument']['diagnostic_measure'])
 def test_tool_38_catalog_gateway_workspace_and_sitemap(self):
  self.assertEqual(self.catalog['actual_tool_count'],38);self.assertEqual(len(self.catalog['tools']),38);row=next(x for x in self.catalog['tools'] if x['id']=='arat');self.assertEqual(row['route'],'/sectors/rehabilitation/measures/action-research-arm-test/');self.assertEqual(row['rights_state'],'rmd-not-free-equipment-operational-sheet-rights-not-public-domain-verified');self.assertIn("arat='/sectors/rehabilitation/measures/action-research-arm-test/'",self.lib);self.assertIn('38 أداة/بطارية فعلية حاليًا',self.gate);self.assertIn('38 أداة/بطارية فعلية',self.work);self.assertIn('38 actual tools',self.finder);urls=[e.text for e in ET.fromstring(self.xml).findall('s:url/s:loc',NS)];self.assertEqual(urls.count('https://healthrenewal.org/sectors/rehabilitation/measures/action-research-arm-test/'),1)
 def test_upper_limb_packet_keeps_constructs_separate(self):
  for text in ('ARAT — قدرة الذراع واليد متعددة المهام','BBT — البراعة اليدوية الإجمالية','9HPT — البراعة الدقيقة للأصابع','Grip Strength — القوة'):self.assertIn(text,self.packets)
  for text in ('ARAT','Grip Strength','BBT','9HPT','PSFS','لا تجمع Grip + BBT + 9HPT + ARAT + PSFS','لا تجمع اليد/الذراع اليمنى واليسرى'):self.assertIn(text,self.upper)
if __name__=='__main__':unittest.main()
