from __future__ import annotations
import json,re,unittest,xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PAGE=ROOT/'sectors'/'rehabilitation'/'measures'/'functional-ambulation-category'/'index.html';JS=PAGE.with_name('fac.js');REG=ROOT/'content'/'global-measures-v1'/'functional-ambulation-category.json';CAT=ROOT/'content'/'global-measures-v1'/'catalog.json';AUDIT=ROOT/'content'/'global-measures-v1'/'rmd-eprovide-rights-audit.json';LIB=ROOT/'sectors'/'rehabilitation'/'measures'/'app.js';SITEMAP=ROOT/'sitemap-rehabilitation-measures.xml';PACKETS=ROOT/'assessments'/'global-measures'/'print-packets'/'index.html';NS={'s':'http://www.sitemaps.org/schemas/sitemap/0.9'}
class FunctionalAmbulationCategoryWave17Test(unittest.TestCase):
 @classmethod
 def setUpClass(cls):cls.html=PAGE.read_text(encoding='utf-8');cls.js=JS.read_text(encoding='utf-8');cls.reg=json.loads(REG.read_text(encoding='utf-8'));cls.catalog=json.loads(CAT.read_text(encoding='utf-8'));cls.audit=json.loads(AUDIT.read_text(encoding='utf-8'));cls.lib=LIB.read_text(encoding='utf-8');cls.xml=SITEMAP.read_text(encoding='utf-8');cls.packets=PACKETS.read_text(encoding='utf-8')
 def test_six_categories_single_choice(self):
  self.assertEqual(len(re.findall(r'name="fac"',self.html)),6)
  for g in range(6):self.assertIn(f'name="fac" value="{g}"',self.html);self.assertIn(f'<span class="fac-grade">{g}</span>',self.html)
 def test_ordinal_no_average_or_total(self):self.assertEqual(self.reg['instrument']['scale_type'],'ordinal');self.assertFalse(self.reg['instrument']['average_for_individual_interpretation']);self.assertIsNone(self.reg['instrument']['global_total_score']);self.assertNotIn('reduce(',self.js);self.assertIn('رتبي وليس فاصلًا',self.html)
 def test_human_assistance_is_primary_and_device_separate(self):self.assertTrue(self.reg['instrument']['human_assistance_is_primary_construct']);self.assertFalse(self.reg['instrument']['walking_aid_determines_category']);self.assertIn('المساعدة البشرية/الإشراف المطلوبان',self.html);self.assertIn('جهاز/دعامة المشي',self.html)
 def test_fac_below_three_not_testable_rule(self):self.assertIn('if(v<3)',self.js);self.assertIn('Not Testable',self.js);self.assertIn('FAC أقل من 3',self.html);self.assertIn('10MWT و6MWT وDGI',self.html);self.assertIn('بدل إعطائها صفرًا',self.html)
 def test_rights_and_arabic_are_conservative(self):
  self.assertEqual(self.reg['rmd']['cost'],'Free');self.assertFalse(self.reg['rights']['instrument_public_domain_verified']);self.assertEqual(self.reg['rights']['rawafid_decision'],'operational-sheet-only');self.assertFalse(self.reg['arabic']['validated_arabic_fac_form_identified_in_this_review']);self.assertFalse(self.reg['arabic']['claim_official_translation']);row=next(x for x in self.audit['current_library'] if x['id']=='fac');self.assertEqual(row['decision'],'operational-sheet-only');self.assertEqual(row['rmd_cost'],'Free');self.assertNotIn('fac',{x['id'] for x in self.audit['priority_candidates']})
 def test_catalog_library_packet_and_sitemap_integration(self):
  self.assertEqual(self.catalog['actual_tool_count'],34);self.assertEqual(len(self.catalog['tools']),34);row=next(x for x in self.catalog['tools'] if x['id']=='fac');self.assertEqual(row['route'],'/sectors/rehabilitation/measures/functional-ambulation-category/');self.assertEqual(row['rights_state'],'rmd-free-operational-paraphrase-rights-not-public-domain-verified');self.assertIn("fac='/sectors/rehabilitation/measures/functional-ambulation-category/'",self.lib);self.assertIn('FAC: استقلالية المشي 0–5 حسب المساعدة البشرية',self.lib);self.assertIn('FAC — استقلالية المشي',self.packets);self.assertIn('FAC&lt;3',self.packets);self.assertIn('Not Testable',self.packets);urls=[e.text for e in ET.fromstring(self.xml).findall('s:url/s:loc',NS)];self.assertEqual(urls.count('https://healthrenewal.org/sectors/rehabilitation/measures/functional-ambulation-category/'),1)
 def test_lifecycle_ids_are_disjoint(self):self.assertTrue({x['id'] for x in self.audit['current_library']}.isdisjoint({x['id'] for x in self.audit['priority_candidates']}))
if __name__=='__main__':unittest.main()
