(() => {
'use strict';
const config=window.PT_SPECIALIST_CONFIG||{};
const SESSION_KEY='ptAdminIdentityV6';
const $=id=>document.getElementById(id);
const state={token:'',expiresAt:'',user:null,coreToken:'',coreExpiresAt:'',users:[],applications:[],providers:[],conversations:[],drafts:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function accountBase(){try{const u=new URL(String(config.accountApiBase||''));return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash?u.href.replace(/\/$/,''):'';}catch(_){return '';}}
function coreBase(){try{const u=new URL(String(config.apiBase||''));return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash?u.href.replace(/\/$/,''):'';}catch(_){return '';}}
function setStatus(message,type='loading'){const b=$('admin-status');b.hidden=false;b.dataset.state=type;b.textContent=message;b.focus?.();}
function fmt(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('ar-JO',{dateStyle:'medium',timeStyle:'short'});}
function label(v){return ({owner:'مالك',admin:'مدير',reviewer:'مراجع',moderator:'مشرف محادثات',specialist:'مختص',invited:'بانتظار التفعيل',active:'نشط',suspended:'موقوف',archived:'مؤرشف',pending:'بانتظار المراجعة',reviewing:'قيد المراجعة',approved:'مقبول',rejected:'مرفوض',withdrawn:'مسحوب',open:'مفتوحة',closed:'مغلقة',blocked:'محظورة',draft:'مسودة',submitted:'مرسلة للمراجعة',published:'منشور',review:'قيد المراجعة',verified:'موثّق',provisional:'تحقق أولي',expired:'منتهي'})[v]||v||'—';}
function save(){sessionStorage.setItem(SESSION_KEY,JSON.stringify({token:state.token,expiresAt:state.expiresAt,coreToken:state.coreToken,coreExpiresAt:state.coreExpiresAt}));}
function load(){try{const x=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(x?.token&&Date.parse(x.expiresAt)>Date.now()){state.token=x.token;state.expiresAt=x.expiresAt;state.coreToken=x.coreToken||'';state.coreExpiresAt=x.coreExpiresAt||'';}}catch(_){sessionStorage.removeItem(SESSION_KEY);}}
function clear(){state.token='';state.expiresAt='';state.user=null;state.coreToken='';state.coreExpiresAt='';sessionStorage.removeItem(SESSION_KEY);}
async function request(root,path,options={},token=''){if(!root)throw new Error('الخدمة غير مربوطة.');const headers=new Headers(options.headers||{});headers.set('accept','application/json');headers.set('x-requested-with','pterminology-admin-v6');if(options.body!=null)headers.set('content-type','application/json;charset=UTF-8');if(token)headers.set('authorization',`Bearer ${token}`);const response=await fetch(`${root}${path}`,{...options,headers,cache:'no-store',credentials:'omit',redirect:'error',referrerPolicy:'no-referrer'});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.message||'تعذر إكمال الطلب.');e.status=response.status;e.code=data.error;throw e;}return data;}
const account=(path,options={},auth=true)=>request(accountBase(),path,options,auth?state.token:'');
const core=(path,options={})=>request(coreBase(),path,options,state.coreToken);
function hashToken(){const q=new URLSearchParams(location.hash.replace(/^#/,'')),t=q.get('resetToken')||'';if(t)history.replaceState(null,document.title,`${location.pathname}${location.search}`);return t;}
function showLogin(){ $('admin-login-shell').hidden=false;$('admin-console').hidden=true; }
function showConsole(){ $('admin-login-shell').hidden=true;$('admin-reset-panel').hidden=true;$('admin-console').hidden=false; }

function initTurnstile(){if(!config.turnstileSiteKey)return;const render=()=>{const target=$('admin-turnstile');if(window.turnstile&&target&&!target.dataset.rendered){window.turnstile.render(target,{sitekey:config.turnstileSiteKey,theme:'light',language:'ar',action:'account_login'});target.dataset.rendered='true';}};if(window.turnstile)render();else{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.defer=true;s.onload=render;document.head.append(s);}}
function turnstile(){return $('admin-turnstile')?.querySelector('[name="cf-turnstile-response"]')?.value||'';}
async function login(event){event.preventDefault();if(!event.currentTarget.reportValidity())return;const token=turnstile();if(config.turnstileSiteKey&&!token){setStatus('أكمل التحقق من الاستخدام البشري.','error');return;}const b=$('admin-login-submit');b.disabled=true;setStatus('جارٍ فتح لوحة الإدارة…');try{const result=await account('/v1/auth/login',{method:'POST',body:JSON.stringify({email:$('admin-email').value.trim(),password:$('admin-password').value,turnstileToken:token})},false);state.token=result.sessionToken;state.expiresAt=result.expiresAt;state.user=result.user;if(!['owner','admin','reviewer','moderator'].includes(state.user.role))throw new Error('هذا الحساب لا يملك صلاحية إدارية.');await ensureCoreSession();save();await refreshAll();showConsole();setStatus('تم تسجيل الدخول بنجاح.','success');}catch(e){clear();showLogin();setStatus(e.message,'error');try{window.turnstile?.reset?.();}catch(_){}}finally{b.disabled=false;}}
async function forgot(){const email=$('admin-email').value.trim();if(!email){setStatus('أدخل البريد أولًا.','error');return;}const token=turnstile();if(config.turnstileSiteKey&&!token){setStatus('أكمل التحقق من الاستخدام البشري.','error');return;}try{const r=await account('/v1/auth/password/request',{method:'POST',body:JSON.stringify({email,turnstileToken:token})},false);setStatus(r.message,'success');try{window.turnstile?.reset?.();}catch(_){}}catch(e){setStatus(e.message,'error');}}
async function resetPassword(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;if($('admin-new-password').value!==$('admin-confirm-password').value){setStatus('كلمتا المرور غير متطابقتين.','error');return;}try{const r=await account('/v1/auth/password/reset',{method:'POST',body:JSON.stringify({token:form.dataset.token,password:$('admin-new-password').value})},false);setStatus(r.message,'success');form.reset();delete form.dataset.token;$('admin-reset-panel').hidden=true;$('admin-login-shell').hidden=false;}catch(e){setStatus(e.message,'error');}}
async function ensureCoreSession(){if(state.coreToken&&Date.parse(state.coreExpiresAt)>Date.now()+60_000)return;const r=await account('/v1/admin/core-session',{method:'POST',body:'{}'});state.coreToken=r.accessToken;state.coreExpiresAt=r.expiresAt;save();}
async function restore(){if(!state.token)return showLogin();try{const r=await account('/v1/auth/session');state.user=r.user;if(!['owner','admin','reviewer','moderator'].includes(state.user.role))throw new Error('لا توجد صلاحية إدارية.');await ensureCoreSession();await refreshAll();showConsole();}catch(e){clear();showLogin();setStatus(e.message,'error');}}
async function logout(){try{await account('/v1/auth/logout',{method:'POST',body:'{}'});}catch(_){}clear();showLogin();setStatus('تم تسجيل الخروج.','success');}

async function refreshAll(){setStatus('جارٍ تحديث بيانات القطاع…');await ensureCoreSession();const [identity,coreOverview]=await Promise.all([account('/v1/admin/overview'),core('/v1/admin/overview')]);$('admin-owner-name').textContent=state.user?.displayNameAr||'الإدارة';$('admin-role-summary').textContent=`${label(state.user?.role)} · تنتهي جلسة الحساب ${fmt(state.expiresAt)} · تنتهي جلسة التشغيل ${fmt(state.coreExpiresAt)}`;$('kpi-users').textContent=identity.users.total;$('kpi-users-detail').textContent=`${identity.users.active} نشطة · ${identity.users.verified} موثقة`;$('kpi-providers').textContent=coreOverview.providers.total;$('kpi-providers-detail').textContent=`${coreOverview.providers.active} نشطة · ${coreOverview.providers.accepting} تستقبل طلبات`;$('kpi-applications').textContent=coreOverview.applications.total;$('kpi-applications-detail').textContent=`${coreOverview.applications.pending} بانتظار المراجعة`;$('kpi-conversations').textContent=coreOverview.conversations.total;$('kpi-conversations-detail').textContent=`${coreOverview.conversations.open} مفتوحة`;$('kpi-drafts').textContent=identity.drafts.total;$('kpi-drafts-detail').textContent=`${identity.drafts.submitted} مرسلة للمراجعة`;await Promise.all([loadUsers(),loadApplications(),loadProviders(),loadConversations(),loadDrafts(),loadAudit()]);setStatus('تم تحديث بيانات القطاع.','success');}

async function loadUsers(){const q=new URLSearchParams({limit:'250'}),search=$('users-search').value.trim(),role=$('users-role-filter').value,status=$('users-status-filter').value;if(search)q.set('q',search);if(role)q.set('role',role);if(status)q.set('status',status);const r=await account(`/v1/admin/users?${q}`);state.users=r.items||[];renderUsers();}
function renderUsers(){const root=$('users-list');root.innerHTML=state.users.length?state.users.map(u=>`<article class="admin-card" data-user-id="${esc(u.id)}"><header class="admin-card-head"><div><p class="eyebrow">${esc(label(u.role))}</p><h3>${esc(u.displayNameAr)}</h3><p>${esc(u.displayNameEn||'')} · ${esc(u.email)}</p></div><span class="badge ${esc(u.status)}">${esc(label(u.status))}</span></header><dl class="admin-details"><dt>الهاتف</dt><dd>${esc(u.phone||'غير مضاف')}</dd><dt>الملف المهني</dt><dd>${esc(u.providerDisplayName||u.providerId||'غير مرتبط')}</dd><dt>التوثيق</dt><dd>${u.verifiedAt?'موثّق '+esc(fmt(u.verifiedAt)):'غير موثّق'}</dd><dt>آخر دخول</dt><dd>${esc(fmt(u.lastLoginAt))}</dd></dl><div class="form-grid compact"><div class="field"><label>الدور</label><select data-field="role">${['owner','admin','reviewer','moderator','specialist'].map(x=>`<option value="${x}" ${u.role===x?'selected':''}>${esc(label(x))}</option>`).join('')}</select></div><div class="field"><label>الحالة</label><select data-field="status">${['invited','active','suspended','archived'].map(x=>`<option value="${x}" ${u.status===x?'selected':''}>${esc(label(x))}</option>`).join('')}</select></div></div><div class="actions"><button class="button secondary" data-action="save-user" type="button">حفظ الصلاحيات</button><button class="button secondary" data-action="verify-user" type="button">تأكيد وتوثيق</button><button class="button secondary" data-action="reset-user" type="button">إرسال رابط إعادة تعيين</button><button class="button danger" data-action="archive-user" type="button">أرشفة الحساب</button></div></article>`).join(''):'<p class="empty">لا توجد حسابات مطابقة.</p>';}
async function createUser(event){event.preventDefault();if(!event.currentTarget.reportValidity())return;setStatus('جارٍ إنشاء الحساب وإرسال رابط التفعيل…');try{await account('/v1/admin/users',{method:'POST',body:JSON.stringify({displayNameAr:$('user-name-ar').value.trim(),displayNameEn:$('user-name-en').value.trim(),email:$('user-email').value.trim(),phone:$('user-phone').value.trim()||null,role:$('user-role').value,providerId:$('user-provider-id').value.trim()||undefined,createProvider:$('user-create-provider').checked})});event.currentTarget.reset();$('user-create-provider').checked=true;await refreshAll();setStatus('تم إنشاء الحساب وإرسال رابط تعيين كلمة المرور.','success');}catch(e){setStatus(e.message,'error');}}
async function userAction(card,action){const id=card.dataset.userId;if(action==='save-user'){await account(`/v1/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({role:card.querySelector('[data-field="role"]').value,status:card.querySelector('[data-field="status"]').value})});setStatus('تم حفظ صلاحيات الحساب.','success');}else if(action==='verify-user'){await account(`/v1/admin/users/${id}/verify`,{method:'POST',body:'{}'});setStatus('تم توثيق الحساب.','success');}else if(action==='reset-user'){await account(`/v1/admin/users/${id}/password-reset`,{method:'POST',body:'{}'});setStatus('تم إرسال رابط إعادة تعيين كلمة المرور.','success');}else if(action==='archive-user'){if(!confirm('أرشفة هذا الحساب وإلغاء جلساته؟'))return;await account(`/v1/admin/users/${id}`,{method:'DELETE',body:JSON.stringify({archiveProvider:false})});setStatus('تمت أرشفة الحساب.','success');}await loadUsers();}

async function loadApplications(){const q=new URLSearchParams({limit:'100'}),f=$('applications-filter').value;if(f)q.set('status',f);const r=await core(`/v1/admin/applications?${q}`);state.applications=r.items||[];const root=$('applications-list');root.innerHTML=state.applications.length?state.applications.map(x=>`<article class="admin-card" data-application-id="${esc(x.id)}"><header class="admin-card-head"><div><p class="eyebrow">${esc(x.referenceId)}</p><h3>${esc(x.displayName)}</h3><p>${esc(x.email)} · ${esc(fmt(x.createdAt))}</p></div><span class="badge ${esc(x.status)}">${esc(label(x.status))}</span></header><details><summary>عرض الطلب</summary><pre>${esc(JSON.stringify(x.payload||{},null,2))}</pre></details><div class="form-grid"><div class="field"><label>الحالة</label><select data-field="status">${['pending','reviewing','approved','rejected','withdrawn'].map(s=>`<option value="${s}" ${x.status===s?'selected':''}>${esc(label(s))}</option>`).join('')}</select></div><div class="field full"><label>ملاحظات إدارية</label><textarea data-field="notes">${esc(x.adminNotes||'')}</textarea></div><div class="field full"><label>رسالة لصاحب الطلب</label><textarea data-field="public-message"></textarea></div></div><button class="button primary" data-action="save-application" type="button">حفظ وإشعار</button></article>`).join(''):'<p class="empty">لا توجد طلبات.</p>';}
async function saveApplication(card){const id=card.dataset.applicationId;await core(`/v1/admin/applications/${id}`,{method:'PATCH',body:JSON.stringify({status:card.querySelector('[data-field="status"]').value,adminNotes:card.querySelector('[data-field="notes"]').value.trim(),publicMessage:card.querySelector('[data-field="public-message"]').value.trim(),notify:true})});setStatus('تم تحديث طلب الانضمام.','success');await Promise.all([loadApplications(),refreshOverviewOnly()]);}
async function loadProviders(){const r=await core('/v1/admin/providers?limit=250');state.providers=r.items||[];const root=$('providers-list');root.innerHTML=state.providers.length?state.providers.map(p=>`<article class="admin-card" data-provider-id="${esc(p.providerId)}"><header class="admin-card-head"><div><p class="eyebrow">${esc(p.providerId)}</p><h3>${esc(p.displayName)}</h3><p>${esc(p.email)} · ${esc(p.profile?.professionalTitle||p.profile?.centerType||'')}</p></div><span class="badge ${esc(p.privateStatus)}">${esc(label(p.privateStatus))}</span></header><dl class="admin-details"><dt>النشر</dt><dd>${esc(label(p.publicationStatus))}</dd><dt>التحقق</dt><dd>${esc(label(p.verificationStatus))}</dd><dt>الموافقة</dt><dd>${esc(label(p.consentStatus))}</dd><dt>المراجعة القادمة</dt><dd>${esc(p.nextReviewAt||'—')}</dd></dl><div class="actions"><button class="button secondary" data-provider-action="suspend" type="button">تعليق</button><button class="button danger" data-provider-action="archive" type="button">أرشفة</button><button class="button secondary" data-provider-action="revoke_consent" type="button">سحب موافقة النشر</button></div></article>`).join(''):'<p class="empty">لا توجد ملفات.</p>';}
async function providerAction(card,action){const id=card.dataset.providerId;if(!confirm(`تنفيذ الإجراء: ${label(action)}؟`))return;await core(`/v1/admin/providers/${id}/actions`,{method:'POST',body:JSON.stringify({action,reason:`admin-${action}`})});setStatus('تم تحديث حالة الملف.','success');await loadProviders();}
async function loadConversations(){const q=new URLSearchParams({limit:'100'}),f=$('conversations-filter').value;if(f)q.set('status',f);const r=await core(`/v1/admin/conversations?${q}`);state.conversations=r.items||[];const root=$('conversations-list');root.innerHTML=state.conversations.length?state.conversations.map(c=>`<article class="admin-card" data-conversation-id="${esc(c.id)}"><header class="admin-card-head"><div><p class="eyebrow">${esc(c.referenceId)}</p><h3>${esc(c.providerDisplayName)}</h3><p>${esc(c.visitorName)} · ${esc(c.topic)} · ${esc(fmt(c.lastMessageAt))}</p></div><span class="badge ${esc(c.status)}">${esc(label(c.status))}</span></header><div class="form-grid"><div class="field"><label>الحالة</label><select data-field="conversation-status">${['open','closed','blocked','archived'].map(s=>`<option value="${s}" ${c.status===s?'selected':''}>${esc(label(s))}</option>`).join('')}</select></div><div class="field full"><label>ملاحظات الإدارة</label><textarea data-field="conversation-notes">${esc(c.adminNotes||'')}</textarea></div></div><button class="button primary" data-action="save-conversation" type="button">حفظ الإجراء</button></article>`).join(''):'<p class="empty">لا توجد محادثات.</p>';}
async function saveConversation(card){const id=card.dataset.conversationId;await core(`/v1/admin/conversations/${id}`,{method:'PATCH',body:JSON.stringify({status:card.querySelector('[data-field="conversation-status"]').value,adminNotes:card.querySelector('[data-field="conversation-notes"]').value.trim()})});setStatus('تم تحديث المحادثة.','success');await loadConversations();}
async function loadDrafts(){const q=new URLSearchParams(),f=$('drafts-filter').value;if(f)q.set('status',f);const r=await account(`/v1/admin/profile-drafts?${q}`);state.drafts=r.items||[];const root=$('drafts-list');root.innerHTML=state.drafts.length?state.drafts.map(d=>`<article class="admin-card" data-draft-id="${esc(d.providerId)}"><header class="admin-card-head"><div><p class="eyebrow">${esc(d.providerId)}</p><h3>${esc(d.displayName)}</h3><p>${esc(d.email||'')} · ${esc(fmt(d.updatedAt))}</p></div><span class="badge ${esc(d.status)}">${esc(label(d.status))}</span></header><details><summary>عرض المسودة</summary><pre>${esc(JSON.stringify(d.data||{},null,2))}</pre></details><div class="field"><label>ملاحظات المراجعة</label><textarea data-field="draft-notes">${esc(d.reviewNotes||'')}</textarea></div><div class="actions"><button class="button primary" data-draft-action="approved" type="button">اعتماد المسودة</button><button class="button danger" data-draft-action="rejected" type="button">رفض وإعادة للمختص</button></div></article>`).join(''):'<p class="empty">لا توجد مسودات.</p>';}
async function reviewDraft(card,decision){await account(`/v1/admin/profile-drafts/${card.dataset.draftId}`,{method:'PATCH',body:JSON.stringify({decision,reviewNotes:card.querySelector('[data-field="draft-notes"]').value.trim()})});setStatus(`تم ${decision==='approved'?'اعتماد':'رفض'} المسودة. هذه الخطوة لا تنشرها للعامة قبل استكمال تحقق الملف المهني.`,'success');await loadDrafts();}
async function loadAudit(){if(state.user?.role!=='owner'){$('audit-list').innerHTML='<p class="empty">سجل التدقيق متاح للمالك فقط.</p>';return;}const r=await account('/v1/admin/identity-audit?limit=200');$('audit-list').innerHTML=(r.items||[]).map(a=>`<article class="audit-row"><time>${esc(fmt(a.createdAt))}</time><strong>${esc(a.eventType)}</strong><span>${esc(a.actorName||a.actorUserId||'النظام')} ← ${esc(a.targetName||a.targetUserId||a.entityId||'—')}</span><code>${esc(JSON.stringify(a.metadata||{}))}</code></article>`).join('')||'<p class="empty">لا يوجد سجل بعد.</p>';}
async function refreshOverviewOnly(){const [i,c]=await Promise.all([account('/v1/admin/overview'),core('/v1/admin/overview')]);$('kpi-users').textContent=i.users.total;$('kpi-providers').textContent=c.providers.total;$('kpi-applications').textContent=c.applications.total;$('kpi-conversations').textContent=c.conversations.total;$('kpi-drafts').textContent=i.drafts.total;}
function tabs(){for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',()=>{for(const x of document.querySelectorAll('[data-tab]'))x.classList.toggle('active',x===b);for(const p of document.querySelectorAll('[data-panel]'))p.classList.toggle('active',p.dataset.panel===b.dataset.tab);});}
function delegate(){document.addEventListener('click',async e=>{const b=e.target.closest('button[data-action],button[data-provider-action],button[data-draft-action]');if(!b)return;b.disabled=true;try{const card=b.closest('.admin-card');if(b.dataset.action?.endsWith('user'))await userAction(card,b.dataset.action);else if(b.dataset.action==='save-application')await saveApplication(card);else if(b.dataset.action==='save-conversation')await saveConversation(card);else if(b.dataset.providerAction)await providerAction(card,b.dataset.providerAction);else if(b.dataset.draftAction)await reviewDraft(card,b.dataset.draftAction);}catch(err){setStatus(err.message,'error');}finally{b.disabled=false;}});}
async function init(){load();initTurnstile();tabs();delegate();$('admin-login-form').addEventListener('submit',login);$('admin-forgot').addEventListener('click',forgot);$('admin-reset-form').addEventListener('submit',resetPassword);$('create-user-form').addEventListener('submit',createUser);$('admin-refresh').addEventListener('click',refreshAll);$('admin-logout').addEventListener('click',logout);$('applications-filter').addEventListener('change',loadApplications);$('conversations-filter').addEventListener('change',loadConversations);$('drafts-filter').addEventListener('change',loadDrafts);for(const id of ['users-search','users-role-filter','users-status-filter'])$(id).addEventListener(id==='users-search'?'input':'change',()=>{clearTimeout(state.userTimer);state.userTimer=setTimeout(loadUsers,250);});const reset=hashToken();if(reset){$('admin-reset-form').dataset.token=reset;$('admin-reset-panel').hidden=false;$('admin-login-shell').hidden=true;return;}await restore();}
init();
})();
