from __future__ import annotations
from scripts.articles_v221_common import BASE,IMAGE,INDEX,NAME,ROUTE,URL,e,foot,head,meta

def article(d):
    schema={'@context':'https://schema.org','@graph':[{'@type':'Article','headline':d['title'],'description':d['description'],'inLanguage':'ar','datePublished':d['reviewed_at'],'dateModified':d['reviewed_at'],'mainEntityOfPage':URL,'author':{'@type':'Organization','name':NAME,'url':BASE},'publisher':{'@type':'Organization','name':NAME,'url':BASE,'logo':{'@type':'ImageObject','url':BASE+'assets/brand/logo-mark.svg'}},'image':IMAGE},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'الرئيسية','item':BASE},{'@type':'ListItem','position':2,'name':'المقالات','item':INDEX},{'@type':'ListItem','position':3,'name':d['title'],'item':URL}]}]}
    quick=''.join(f'<li>{e(x)}</li>' for x in d['quick_answer'])
    rows=''.join(f'<tr><th scope="row">{e(x["dimension"])}</th><td>{e(x["normal"])}</td><td>{e(x["concern"])}</td></tr>' for x in d['comparison'])
    sections=''.join(f'<section><h2>{e(s["heading"])}</h2>'+''.join(f'<p>{e(p)}</p>' for p in s['paragraphs'])+'</section>' for s in d['sections'][:-1])
    urgent=d['sections'][-1]
    urgent_html='<section class="urgent"><h2>'+e(urgent['heading'])+'</h2>'+''.join(f'<p>{e(p)}</p>' for p in urgent['paragraphs'])+'</section>'
    myths=''.join(f'<article class="myth"><h3>{e(x["myth"])}</h3><p><strong>التوضيح:</strong> {e(x["fact"])}</p></article>' for x in d['myths'])
    fields=''.join(f'<li>{e(x)}</li>' for x in d['seven_day_fields'])
    links=''.join(f'<li><a href="{e(x["href"])}">{e(x["label"])}</a></li>' for x in d['internal_links'])
    sources=''.join(f'<li><a rel="noopener noreferrer" href="{e(x["url"])}">{e(x["title"])}</a> — {e(x["publisher"])} ({x["year"]})</li>' for x in d['sources'])
    return f'''<!doctype html><html lang="ar" dir="rtl"><head>{meta(d['title'],d['description'],URL,d['keywords'],schema)}</head><body>{head()}<main><nav class="crumb" aria-label="مسار التنقل"><a href="/pterminology-site/">الرئيسية</a> ← <a href="/pterminology-site/articles/">المقالات</a> ← <span aria-current="page">{e(d['title'])}</span></nav><article><header class="hero"><span class="tag">دليل تثقيفي غير تشخيصي</span><h1>{e(d['title'])}</h1><p class="lead">{e(d['summary'])}</p><p class="meta">آخر مراجعة داخلية للمصادر: {d['reviewed_at']}</p></header><section class="limit"><h2>الإجابة المباشرة</h2><ul class="quick">{quick}</ul></section><section><h2>مقارنة عملية</h2><div class="scroll"><table><thead><tr><th>البعد</th><th>قلق طبيعي غالبًا</th><th>مؤشرات تستحق التقييم</th></tr></thead><tbody>{rows}</tbody></table></div></section>{sections}<section><h2>ورقة ملاحظة سبعة أيام</h2><p>اكتب أقل قدر مفيد مرة أو مرتين يوميًا. لا تستخدم السجل كاختبار أو لمراقبة الجسد طوال الوقت.</p><ul class="grid fields">{fields}</ul></section><section><h2>أفكار شائعة تحتاج تصحيحًا</h2><div class="grid">{myths}</div></section>{urgent_html}<section class="limit"><h2>حدود هذا المقال</h2><p>لا يشخّص المقال اضطرابًا، ولا يحدد سبب الأعراض، ولا يوصي بدواء أو تغيير جرعة. التقييم المهني يجمع السياق والوظيفة والصحة الجسدية والأدوية والمواد المستخدمة والتاريخ النفسي.</p></section><section><h2>مسارات مرتبطة</h2><ul>{links}</ul></section><section><h2>المصادر الرسمية</h2><ul>{sources}</ul></section></article></main>{foot()}</body></html>'''

def index_page(d):
    desc='مقالات عربية موثوقة في الصحة النفسية تشرح الفروق والخطوات العملية وحدود التفسير، وتربط المعرفة بالمصادر وطلب المساعدة الآمن.'
    schema={'@context':'https://schema.org','@type':'CollectionPage','name':'مقالات الصحة النفسية','description':desc,'url':INDEX,'inLanguage':'ar','hasPart':[{'@type':'Article','name':d['title'],'url':URL}]}
    return f'''<!doctype html><html lang="ar" dir="rtl"><head>{meta('مقالات الصحة النفسية',desc,INDEX,['مقالات الصحة النفسية','علم النفس بالعربي','القلق','مصطلحات علم النفس'],schema,'website')}</head><body>{head()}<main><header class="hero"><span class="tag">مقالات تحليلية عملية</span><h1>مقالات الصحة النفسية</h1><p class="lead">{desc}</p></header><section><h2>أحدث المقالات</h2><article class="card"><h3>{e(d['title'])}</h3><p>{e(d['description'])}</p><a class="button" href="/pterminology-site/{ROUTE}">قراءة المقال</a></article></section><section class="limit"><h2>منهج النشر</h2><p>كل مادة تحتاج مصادر رسمية وروابط داخلية وحدود تفسير وطلب مساعدة آمن.</p><a href="/pterminology-site/trust/">منهج المصادر والمراجعة</a></section></main>{foot()}</body></html>'''
