#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

BASE = "https://healthrenewal.org/sections/research-evidence-learning/"
SECTION = "البحث والدليل والتعلم"
VERSION = 1

@dataclass(frozen=True)
class Topic:
    slug: str
    title: str
    definition: str
    value: str
    risks: str
    example: str
    sources: tuple[tuple[str, str], ...]

TOPICS = (
    Topic("systematic-reviews", "المراجعات المنهجية", "منهج منظم لصياغة سؤال محدد والبحث الشامل عن الدراسات ذات الصلة وتقييمها وتجميع نتائجها وفق بروتوكول واضح.", "تساعد على رؤية الصورة الكلية بدل الاعتماد على دراسة منفردة، وتكشف اتساق النتائج واختلافها والفجوات البحثية.", "أبرز المخاطر هي البحث غير الشامل، معايير إدراج متحيزة، ازدواج العد، ضعف تقييم خطر التحيز، أو تفسير التجميع كأنه يقين مطلق.", "عند مراجعة تدخل مدرسي لخفض القلق، يجب تعريف الفئة والتدخل والمقارنة والنتائج أولًا ثم البحث في قواعد متعددة وتوثيق أسباب الاستبعاد.", (("PRISMA 2020", "https://www.prisma-statement.org/prisma-2020"), ("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"))),
    Topic("meta-analysis", "التحليل التلوي", "أسلوب إحصائي لدمج تقديرات كمية من دراسات قابلة للمقارنة لإنتاج تقدير إجمالي مع قياس عدم اليقين والتغاير.", "يوضح حجم الأثر واتجاهه ومدى تباين النتائج بين الدراسات، ويمكن أن يدعم استكشاف أسباب الاختلاف.", "قد يكون مضللًا إذا جُمعت دراسات غير متجانسة مفاهيميًا أو استخدمت نماذج غير مناسبة أو أُهمل تحيز النشر والدراسات الصغيرة.", "دمج نتائج خمس تجارب لا يصبح ذا معنى لمجرد إمكان حساب المتوسط؛ يجب أولًا التأكد من أن التدخلات والنتائج والسياقات متقاربة بما يكفي.", (("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("PRISMA 2020", "https://www.prisma-statement.org/prisma-2020"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"))),
    Topic("randomized-trials", "التجارب العشوائية المضبوطة", "تصميم تجريبي يوزع المشاركين عشوائيًا على تدخلات أو مقارنات لتقليل الاختلافات المنهجية بين المجموعات عند خط الأساس.", "عندما تُنفذ جيدًا تكون قوية لتقدير الأثر السببي للتدخلات، خصوصًا مع إخفاء التخصيص وتحليل مناسب وفقد متابعة محدود.", "التحيز قد يدخل من سوء العشوائية أو كشف التخصيص أو الانسحاب غير المتوازن أو تبديل النتائج أو التحليل الانتقائي.", "في تجربة برنامج تدريب انتباه، لا تكفي كلمة عشوائي؛ يجب معرفة طريقة إنشاء التسلسل، إخفاء التخصيص، التعامل مع الغياب، وما إذا كانت النتيجة محددة مسبقًا.", (("CONSORT 2025", "https://www.equator-network.org/reporting-guidelines/consort/"), ("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"))),
    Topic("observational-studies", "الدراسات الرصدية", "دراسات تراقب التعرضات والنتائج دون تعيين عشوائي للتعرض، وتشمل الأتراب والحالات والشواهد والمقاطع العرضية.", "مهمة لدراسة التعرضات التي لا يمكن أو لا ينبغي تعيينها تجريبيًا، وللآثار بعيدة المدى والانتشار والارتباطات الواقعية.", "الخلط والانتقاء والتحيز في القياس والسببية العكسية قد تجعل الارتباط يبدو سببيًا وهو ليس كذلك.", "وجود ارتباط بين وقت الشاشة والنوم لا يثبت أن أحدهما سبب الآخر دون فحص العمر والروتين والصحة النفسية والاتجاه الزمني وعوامل أخرى.", (("STROBE", "https://www.equator-network.org/reporting-guidelines/strobe/"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"), ("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"))),
    Topic("cohort-studies", "دراسات الأتراب", "تصميم يتابع مجموعة محددة عبر الزمن لمقارنة حدوث النتائج بحسب تعرضات أو خصائص مختلفة.", "يفيد في ترتيب التعرض قبل النتيجة وحساب المخاطر ومتابعة التطور الطبيعي والنتائج طويلة الأجل.", "الفقد في المتابعة، تغير التعرض مع الزمن، والخلط المتبقي قد يشوه التقديرات.", "إذا تابعت دراسة أطفالًا لسنوات، افحص من انسحب ولماذا وهل اختلف المنسحبون عن الباقين، وكيف تغيرت القياسات خلال المتابعة.", (("STROBE", "https://www.equator-network.org/reporting-guidelines/strobe/"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"), ("NIH", "https://www.nih.gov/"))),
    Topic("case-control", "دراسات الحالات والشواهد", "تصميم يبدأ بأشخاص لديهم نتيجة محددة وآخرين دونها ثم يقارن التعرضات السابقة بين المجموعتين.", "فعال نسبيًا للنتائج النادرة أو ذات الكمون الطويل، ويسمح بفحص عدة تعرضات محتملة.", "اختيار الشواهد والتحيز في تذكر التعرض وصعوبة إثبات التسلسل الزمني من أهم القيود.", "في دراسة عامل خطر نادر، يجب أن يمثل الشواهد المجتمع الذي جاءت منه الحالات، وإلا قد يتغير تقدير الارتباط جذريًا.", (("STROBE", "https://www.equator-network.org/reporting-guidelines/strobe/"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"), ("NIH", "https://www.nih.gov/"))),
    Topic("cross-sectional", "الدراسات المقطعية", "دراسات تقيس التعرض والنتيجة في نقطة زمنية أو نافذة قصيرة واحدة، وغالبًا تستخدم لوصف الانتشار والارتباط.", "سريعة ومفيدة لرسم صورة حالية وتحديد احتياجات أو فرضيات بحثية تستحق المتابعة.", "يصعب منها تحديد أي المتغيرين سبق الآخر، وقد تتأثر بتحيز عدم الاستجابة والقياس الذاتي.", "إذا وجد مسح مدرسي علاقة بين الضغط والغياب في الشهر نفسه، فالنتيجة تصلح لوصف الارتباط لكنها لا تحسم اتجاه السببية.", (("STROBE", "https://www.equator-network.org/reporting-guidelines/strobe/"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"), ("WHO", "https://www.who.int/"))),
    Topic("qualitative-research", "البحث النوعي", "مجموعة مناهج تستكشف الخبرة والمعنى والسياق والعمليات باستخدام مقابلات أو ملاحظة أو مجموعات تركيز أو مواد نصية وغيرها.", "يكشف كيف يفهم الناس التجارب ولماذا تنجح الممارسات أو تفشل في سياقات بعينها، ويضيف عمقًا لا تمنحه المقاييس الكمية وحدها.", "ضعف الشفافية في أخذ العينة والترميز وانعكاسية الباحث وسياق جمع البيانات قد يجعل الاستنتاجات غير قابلة للتقييم.", "عند دراسة تجربة أسر مع خدمة دعم، قيمة البحث ليست في عدّ الإجابات فقط بل في تحليل الأنماط والسياقات والحالات المخالفة وشفافية الانتقال من البيانات إلى الاستنتاج.", (("COREQ", "https://www.equator-network.org/reporting-guidelines/coreq/"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"), ("NIH", "https://www.nih.gov/"))),
    Topic("mixed-methods", "البحوث المختلطة", "تصميم يدمج بيانات كمية ونوعية داخل دراسة أو برنامج بحثي واحد للإجابة عن جوانب مختلفة من السؤال.", "يمكنه الجمع بين تقدير الحجم وفهم الآلية والسياق، ويكون مفيدًا عندما لا تكفي إجابة رقمية أو وصفية منفردة.", "مجرد وضع استبيان ومقابلات في المشروع لا يحقق دمجًا حقيقيًا؛ يجب توضيح سبب الدمج ونقطة التكامل وكيف تؤثر النتائج بعضها في بعض.", "قد يبين القياس أن البرنامج حسن الحضور، بينما توضح المقابلات أن التحسن حدث فقط عندما كانت الجلسات مرنة ومناسبة للحساسيات الحسية.", (("NIH", "https://www.nih.gov/"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"), ("WHO", "https://www.who.int/"))),
    Topic("risk-of-bias", "خطر التحيز", "تقييم منهجي لاحتمال أن تؤدي خصائص تصميم الدراسة أو تنفيذها أو تحليلها أو تقريرها إلى انحراف النتائج عن الحقيقة.", "يفصل بين جودة العرض ومصداقية التقدير؛ فقد تكون الدراسة مكتوبة جيدًا لكن معرضة لتحيز مهم.", "تحويل التقييم إلى درجة إجمالية مبسطة قد يخفي اختلاف مصادر التحيز واتجاهها وتأثيرها على كل نتيجة.", "النتيجة الإيجابية لا تكفي؛ اسأل هل عُرفت النتيجة بعد رؤية البيانات، وهل كان فقد المتابعة مرتبطًا بالاستجابة، وهل القياس متساوٍ بين المجموعات.", (("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("ROBINS-I", "https://www.riskofbias.info/"), ("EQUATOR", "https://www.equator-network.org/"))),
    Topic("confounding", "الخلط والعوامل المربكة", "يحدث الخلط عندما يرتبط عامل ثالث بالتعرض والنتيجة فيشوّه تقدير العلاقة بينهما إذا لم يُصمم أو يُحلل البحث لمعالجته.", "فهم الخلط أساسي لقراءة الدراسات الرصدية وعدم تحويل الارتباط إلى ادعاء سببي متسرع.", "الضبط الزائد لعوامل تقع على المسار السببي أو اختيار مربكات بعد رؤية النتائج قد يسبب تحيزًا جديدًا بدل إصلاحه.", "إذا ارتبط الدعم الأسري بالتحصيل، فقد يكون دخل الأسرة أو جودة المدرسة مرتبطين بالدعم والتحصيل معًا ويحتاجان إلى تفكير سببي قبل الضبط.", (("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("STROBE", "https://www.equator-network.org/reporting-guidelines/strobe/"), ("NIH", "https://www.nih.gov/"))),
    Topic("effect-size", "حجم الأثر", "مقياس يصف مقدار الفرق أو العلاقة بصورة تتجاوز مجرد وجود دلالة إحصائية، مثل فرق المتوسط أو النسبة أو الارتباط أو المقاييس المعيارية.", "يساعد في الحكم على أهمية النتيجة عمليًا ومقارنتها بالسياق وخط الأساس وعدم اليقين.", "قد يبدو الأثر كبيرًا على مقياس معياري لكنه صغير عمليًا، كما أن انتقاء مقياس أثر ملائم بعد النتائج يمكن أن يضلل.", "تحسن درجتين قد يكون مهمًا أو هامشيًا حسب نطاق المقياس وخطر الأساس وحد التغير المهم للمستخدمين.", (("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("CONSORT", "https://www.equator-network.org/reporting-guidelines/consort/"), ("GRADE", "https://www.gradeworkinggroup.org/"))),
    Topic("confidence-intervals", "فترات الثقة وعدم اليقين", "فترة حول التقدير الإحصائي تعكس مقدار عدم اليقين المتوافق مع البيانات والنموذج المستخدم، ولا تعني أن كل قيمة داخلها متساوية الاحتمال.", "تجبر القارئ على النظر إلى دقة التقدير والنتائج المعقولة بدل اختزال الدراسة إلى دال أو غير دال.", "تفسير الفترة كضمان لاحتمال فردي أو تجاهل اتساعها أو التركيز على عبورها الصفر فقط من الأخطاء الشائعة.", "أثر مقداره 0.30 مع فترة من -0.05 إلى 0.65 يختلف معرفيًا عن 0.30 مع فترة من 0.25 إلى 0.35 رغم تطابق التقدير النقطي.", (("CONSORT", "https://www.equator-network.org/reporting-guidelines/consort/"), ("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("GRADE", "https://www.gradeworkinggroup.org/"))),
    Topic("statistical-significance", "الدلالة الإحصائية", "مفهوم يقيّم مدى توافق البيانات مع فرضية ونموذج محددين، وغالبًا يُختزل خطأ إلى عتبة قيمة احتمالية واحدة.", "يمكن أن تكون جزءًا من الاستدلال إذا قُرئت مع حجم الأثر وفترة عدم اليقين والتصميم والافتراضات.", "الخلط بين الدلالة والأهمية العملية، أو اعتبار p أكبر من 0.05 دليلًا على عدم وجود أثر، أو مطاردة العتبة يؤدي لاستنتاجات رديئة.", "نتيجة p=0.049 ليست نوعيًا أقوى من p=0.051؛ الأهم هو حجم التقدير ودقته وجودة التصميم وتوافقه مع الأدلة الأخرى.", (("CONSORT", "https://www.equator-network.org/reporting-guidelines/consort/"), ("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("NIH", "https://www.nih.gov/"))),
    Topic("power-sample-size", "القوة الإحصائية وحجم العينة", "تخطيط يربط حجم العينة بالأثر المراد اكتشافه والتباين ومستوى الخطأ وتصميم الدراسة، مع مراعاة الانسحاب والعناقيد عند الحاجة.", "يقلل الدراسات الصغيرة غير الحاسمة والهدر، ويساعد على تقدير موارد مناسبة لسؤال محدد مسبقًا.", "اختيار أثر متوقع غير واقعي أو حساب القوة بعد رؤية النتيجة أو تجاهل تصميم العناقيد قد يعطي ثقة زائفة.", "برنامج مدرسي موزع على صفوف يحتاج حسابًا يراعي تشابه الطلاب داخل الصف، وليس معاملتهم كأفراد مستقلين تمامًا.", (("CONSORT", "https://www.equator-network.org/reporting-guidelines/consort/"), ("NIH", "https://www.nih.gov/"), ("EQUATOR", "https://www.equator-network.org/"))),
    Topic("diagnostic-accuracy", "دقة الاختبارات التشخيصية", "تقييم قدرة اختبار على التمييز بين وجود حالة مرجعية وعدمها باستخدام الحساسية والنوعية والنسب الاحتمالية ومقاييس أخرى.", "مهم لفهم ما إذا كان الاختبار مناسبًا للاستبعاد أو التأكيد وكيف تتغير قيمة النتيجة باختلاف احتمال ما قبل الاختبار.", "التحقق الجزئي، معيار مرجعي ضعيف، انتقاء عينة سهلة، أو اختيار العتبة بعد البيانات يضخم الأداء.", "حساسية 90% لا تعني أن 90% من النتائج الإيجابية صحيحة؛ القيمة التنبؤية تعتمد أيضًا على انتشار الحالة في السكان المستخدمين.", (("STARD", "https://www.equator-network.org/reporting-guidelines/stard/"), ("EQUATOR", "https://www.equator-network.org/reporting-guidelines/"), ("Cochrane", "https://www.cochrane.org/"))),
    Topic("reliability", "الثبات في القياس", "مدى اتساق نتائج القياس عبر الزمن أو المقيمين أو البنود وفق نوع الثبات المقصود وشروط الاستخدام.", "الثبات شرط مهم للتفسير لأنه يحدد مقدار الضجيج الذي قد يحجب التغير أو الفروق الحقيقية.", "ارتفاع الاتساق الداخلي وحده لا يثبت أن الأداة تقيس بناء واحدًا ولا يثبت الصدق أو الملاءمة الفردية.", "إذا تغير تقييم الطفل كثيرًا بين مقيمين مدربين دون سبب سريري، يجب فحص ثبات المقيمين قبل تفسير الفروق كاختلاف حقيقي.", (("COSMIN", "https://www.cosmin.nl/"), ("NIH", "https://www.nih.gov/"), ("EQUATOR", "https://www.equator-network.org/"))),
    Topic("validity", "الصدق وصلاحية التفسير", "مجموعة أدلة تدعم تفسير درجات أداة أو استنتاجات دراسة للغرض والسكان والسياق المحدد، وليس صفة ثابتة للأداة في كل مكان.", "يمنع نقل النتائج من سياق إلى آخر دون دليل، ويجبر الباحث على ربط القياس بالبناء النظري والنتائج الخارجية والاستعمال المقصود.", "القول إن الأداة صادقة لأنها ترتبط بأداة أخرى فقط، أو ترجمتها دون فحص بنيوي وثقافي، من الاختصارات غير الكافية.", "مقياس مترجم قد يحافظ على الكلمات لكنه لا يحافظ على معنى البنود أو بنيتها لدى فئة جديدة؛ لذلك يلزم فحص أدلة الصلاحية في السياق الجديد.", (("COSMIN", "https://www.cosmin.nl/"), ("NIH", "https://www.nih.gov/"), ("WHO", "https://www.who.int/"))),
    Topic("grade-certainty", "يقين الدليل ومنهج GRADE", "إطار منظم لتقدير مدى الثقة في تقدير أثر عبر نتائج مهمة بالاعتماد على خطر التحيز وعدم الاتساق وعدم المباشرة وعدم الدقة وعوامل أخرى.", "يساعد على الفصل بين حجم الأثر ودرجة الثقة فيه، ويجعل سبب خفض أو رفع اليقين قابلًا للتدقيق.", "استخدام تصنيف عام للدراسة بدل تقييم كل نتيجة، أو مساواة يقين منخفض بعدم وجود أثر، من الأخطاء الجوهرية.", "قد يكون الأثر كبيرًا لكن اليقين منخفضًا بسبب عينات صغيرة وعدم اتساق، فيجب وصف الاثنين بدل تقديم النتيجة كحقيقة مستقرة.", (("GRADE", "https://www.gradeworkinggroup.org/"), ("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("WHO", "https://www.who.int/"))),
    Topic("critical-appraisal", "التقييم النقدي للدراسات", "عملية منظمة لفحص سؤال الدراسة وتصميمها وتنفيذها وتحليلها وتقريرها ومدى قابلية تطبيق نتائجها.", "يحمي من الانبهار بعنوان أو مجلة أو نتيجة مثيرة ويحوّل القراءة إلى سلسلة أسئلة قابلة للتحقق.", "القوائم الآلية التي تمنح نقاطًا دون فهم التصميم قد تساوي أخطاء غير متساوية وتخفي مشكلة حاسمة واحدة.", "ابدأ بالسؤال والنتيجة المقصودة، ثم التصميم والعينة والقياس والتحليل، وبعدها اسأل كيف يمكن لكل خلل أن يغير النتيجة واتجاهه المحتمل.", (("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("EQUATOR", "https://www.equator-network.org/"), ("GRADE", "https://www.gradeworkinggroup.org/"))),
    Topic("preregistration", "التسجيل المسبق والبروتوكولات", "توثيق الأسئلة والفرضيات والنتائج وخطة التحليل أو بروتوكول المراجعة قبل الاطلاع الكامل على النتائج، مع حفظ تعديلات لاحقة بشفافية.", "يقلل المرونة الخفية والانتقائية ويسمح للقارئ بالتمييز بين التحليل المؤكد والاستكشافي.", "التسجيل الغامض أو المتأخر أو تعديل النتائج دون توضيح لا يحقق الغرض، كما أن التسجيل لا يضمن جودة المنهج نفسه.", "إذا تغيرت النتيجة الأساسية بعد بدء التحليل، يمكن أن يكون التغيير مبررًا، لكن يجب توثيق متى ولماذا بدل تقديمه كأنه الخطة الأصلية.", (("OSF", "https://www.cos.io/products/osf"), ("PRISMA-P", "https://www.equator-network.org/reporting-guidelines/prisma-protocols/"), ("EQUATOR", "https://www.equator-network.org/"))),
    Topic("open-science", "العلم المفتوح وقابلية التكرار", "ممارسات تزيد شفافية دورة البحث مثل مشاركة البروتوكولات والمواد والكود والبيانات عندما تكون أخلاقيًا وقانونيًا مناسبة.", "تجعل التدقيق وإعادة التحليل والتعلم من الأخطاء أسهل وتقلل الاعتماد على وصف لا يمكن فحصه.", "الانفتاح لا يعني نشر بيانات حساسة، كما أن وجود مستودع لا يعوض توثيقًا ضعيفًا أو كودًا غير قابل للتشغيل.", "في بيانات الأطفال أو الصحة النفسية، قد تكون مشاركة قاموس البيانات والكود والبيانات الاصطناعية أفضل من نشر سجلات يمكن إعادة التعرف على أصحابها.", (("Center for Open Science", "https://www.cos.io/"), ("NIH Data Management", "https://sharing.nih.gov/"), ("WHO", "https://www.who.int/"))),
    Topic("publication-bias", "تحيز النشر والنتائج المفقودة", "انحراف الأدبيات المنشورة عندما تعتمد احتمالية ظهور دراسة أو نتيجة على اتجاهها أو دلالتها أو جاذبيتها.", "فهمه ضروري لأن مجموعة الدراسات المتاحة قد تعطي أثرًا أكبر أو أكثر يقينًا من كل الأدلة المنجزة فعليًا.", "مخطط القمع وحده لا يثبت تحيز النشر، واختبارات عدم التماثل ضعيفة مع عدد قليل من الدراسات وتتأثر بعدم التجانس.", "إذا اختفت دراسات صغيرة سلبية من الأدبيات، قد يبدو التدخل أنفع مما هو؛ لذلك تفيد السجلات والبروتوكولات والبحث عن نتائج غير منشورة.", (("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"), ("PRISMA", "https://www.prisma-statement.org/"), ("WHO ICTRP", "https://trialsearch.who.int/"))),
    Topic("causal-inference", "الاستدلال السببي", "مجموعة مفاهيم وتصاميم وتحليلات تهدف إلى تقدير ما كان سيحدث للنتيجة تحت تدخل أو تعرض بديل مع توضيح الافتراضات اللازمة.", "يساعد على صياغة السؤال السببي وتحديد المربكات والوسطاء والانحيازات بدل الاعتماد على الارتباط الخام.", "نماذج إحصائية معقدة لا تنقذ سؤالًا سببيًا غامضًا، والافتراضات غير القابلة للاختبار تحتاج تبريرًا وحساسيات.", "قبل ضبط كل المتغيرات المتاحة، ارسم منطق العلاقة: بعض المتغيرات مربكات، وبعضها وسطاء، وبعضها قد يفتح مسار تحيز إذا ضُبط.", (("NIH", "https://www.nih.gov/"), ("STROBE", "https://www.equator-network.org/reporting-guidelines/strobe/"), ("Cochrane", "https://www.cochrane.org/"))),
    Topic("implementation-science", "علم التنفيذ", "دراسة كيفية إدخال الممارسات المدعومة بالدليل والمحافظة عليها وتكييفها في الخدمات الواقعية مع قياس القبول والالتزام والوصول والاستدامة.", "يسد الفجوة بين فعالية تدخل في دراسة محكمة وقدرته على العمل داخل مدرسة أو عيادة أو مجتمع حقيقي.", "التركيز على النتيجة النهائية دون قياس ما إذا نُفذ التدخل كما قصد أو لماذا تغير يجعل فشل التنفيذ يختلط بفشل التدخل.", "قد يكون البرنامج فعالًا نظريًا لكنه يفشل لأن التدريب غير كافٍ أو الوقت غير متاح؛ قياس التنفيذ يحدد أين حدث الانقطاع.", (("NIH", "https://www.nih.gov/"), ("WHO", "https://www.who.int/"), ("EQUATOR", "https://www.equator-network.org/"))),
    Topic("evidence-based-practice", "الممارسة المبنية على الدليل", "دمج أفضل دليل بحثي متاح مع الخبرة المهنية وقيم الشخص واحتياجاته وسياقه وموارده، بدل تطبيق نتائج الدراسة بصورة آلية.", "تحول الدليل إلى قرار مشترك قابل للتطبيق وتمنع مساواة الدليل الإحصائي بالحكم الفردي النهائي.", "الانتقائية في الاستشهاد، تجاهل تفضيلات الشخص، أو استعمال عبارة مبني على الدليل دون تحديد نوع الدليل وجودته كلها ممارسات مضللة.", "قد يكون تدخل ما مدعومًا بمتوسط أثر جيد، لكن القرار الفردي يحتاج ملاءمة العمر واللغة والحساسيات والأهداف وإمكان الوصول والمتابعة.", (("Cochrane", "https://www.cochrane.org/"), ("GRADE", "https://www.gradeworkinggroup.org/"), ("WHO", "https://www.who.int/"))),
    Topic("education-evidence", "الدليل في التعليم والتربية الدامجة", "تطبيق مناهج تقييم الدليل على التدخلات والسياسات التعليمية مع الانتباه للعناقيد المدرسية والسياق والنتائج الأكاديمية والوظيفية والرفاه.", "يساعد المدارس والأسر على التمييز بين الممارسات الواعدة والتوصيات المدعومة بتجارب أو توليفات جيدة.", "نقل نتائج من مدرسة أو فئة مختلفة دون فحص السياق، أو الاعتماد على تحسن درجات اختبار واحد، قد يبالغ في قابلية التعميم.", "تقييم استراتيجية صفية يحتاج النظر إلى مستوى الطالب والصف والمدرسة، وفحص التنفيذ والنتائج الجانبية وإمكان التطبيق لا مجرد قيمة احتمالية.", (("What Works Clearinghouse", "https://ies.ed.gov/ncee/wwc/"), ("Campbell Collaboration", "https://www.campbellcollaboration.org/"), ("UNESCO", "https://www.unesco.org/"))),
    Topic("research-ethics", "أخلاقيات البحث والخصوصية", "مبادئ وإجراءات لحماية المشاركين واحترام الاستقلال وتقليل الضرر وتحقيق العدالة وحماية البيانات، مع مراجعة أخلاقية مناسبة للسياق.", "تحدد ما إذا كان البحث مقبولًا أصلًا، لا مجرد ما إذا كان التصميم قادرًا على إنتاج نتيجة دقيقة.", "موافقة شكلية غير مفهومة، جمع بيانات أكثر من الحاجة، أو نشر تفاصيل قابلة لإعادة التعرف قد يضر المشاركين حتى لو كانت النية علمية.", "في بحث مع أطفال أو فئات ضعيفة، يجب أن تكون الموافقة والموافقة المساندة والانسحاب والسرية وخطة الإحالة مفهومة ومناسبة للمخاطر الفعلية.", (("WHO Research Ethics", "https://www.who.int/ethics/research/en/"), ("NIH Human Subjects", "https://grants.nih.gov/policy/humansubjects.htm"), ("UNESCO Bioethics", "https://www.unesco.org/en/ethics-science-technology/bioethics"))),
)

INTENTS = (
    ("basics", "الأساسيات التي يجب فهمها", "تعريف المفهوم وحدوده وما الذي يجيب عنه وما الذي لا يجيب عنه."),
    ("read-paper", "كيف تقرأ دراسة", "مسار قراءة عملي يبدأ بالسؤال ثم التصميم والعينة والقياس والتحليل والنتائج والقيود."),
    ("critical-checklist", "قائمة تقييم نقدي", "أسئلة فحص مرتبة لاكتشاف المشكلات التي قد تغيّر الثقة في النتيجة."),
    ("common-errors", "الأخطاء الشائعة", "الأخطاء المفاهيمية والتحليلية والتقريرية التي تتكرر عند تفسير هذا النوع من الأدلة."),
    ("interpret-results", "تفسير النتائج", "طريقة الانتقال من الرقم إلى معنى منضبط يراعي حجم الأثر وعدم اليقين والسياق."),
    ("bias", "التحيز ومصادره", "أهم مسارات التحيز المحتملة وكيف يمكن أن تدفع النتيجة في اتجاه مضلل."),
    ("reporting", "التقرير العلمي والشفافية", "ما الذي يجب الإبلاغ عنه كي يتمكن القارئ من تقييم العمل وإعادة فهمه."),
    ("design", "تصميم دراسة قوية", "قرارات التصميم المسبقة التي تحسن قابلية الإجابة وتقلل المرونة والتحيز."),
    ("analysis", "التحليل الإحصائي أو المنهجي", "اختيار التحليل بما يتوافق مع السؤال والتصميم والافتراضات بدل اختيار الطريقة بعد رؤية النتائج."),
    ("example", "مثال تطبيقي مشروح", "مثال تعليمي يوضح كيف تتغير القراءة عندما نفحص المنهج والسياق بدل الاكتفاء بالخلاصة."),
    ("compare", "مقارنة مع البدائل", "متى يكون هذا النهج أنسب أو أضعف من تصاميم أو أدوات أخرى وما المقايضة بينهما."),
    ("quality", "كيف تحكم على الجودة", "تمييز جودة التصميم والتنفيذ والتقرير عن حجم النتيجة وجاذبيتها."),
    ("certainty", "ما درجة الثقة في الاستنتاج", "فحص مباشر لمدى اليقين وما الذي يمكن أن يغير القرار لو ظهرت بيانات جديدة."),
    ("application", "التطبيق في الواقع", "ترجمة الدليل إلى قرار مع مراعاة السكان والسياق والموارد والقيم وقابلية التنفيذ."),
    ("school", "التطبيق في المدرسة", "أسئلة خاصة بالسياق المدرسي والعناقيد والتنفيذ والإنصاف والنتائج الوظيفية."),
    ("family", "ما الذي يعنيه للأسرة", "كيف تشرح النتيجة للأسرة دون تهويل أو تشخيص أو تحويل متوسطات المجموعات إلى تنبؤ فردي."),
    ("professional", "دليل للمختص", "طريقة دمج النتيجة مع التقييم المهني والبدائل ومراقبة الاستجابة والقرار المشترك."),
    ("researcher", "دليل للباحث", "خطوات قبل جمع البيانات وأثناء التحليل وعند التقرير تساعد على إنتاج سجل بحثي قابل للتدقيق."),
    ("questions", "20 سؤالًا قبل أن تصدق الادعاء", "أسئلة سريعة تكشف ما إذا كانت الخلاصة أقوى من تصميم الدراسة أو بياناتها."),
    ("advanced", "قراءة متقدمة", "تفاصيل أعمق حول الافتراضات والحساسيات والتعميم وكيفية التعامل مع الأدلة المتعارضة."),
)

COMMON_SOURCES = (
    ("EQUATOR Network", "https://www.equator-network.org/reporting-guidelines/"),
    ("Cochrane Handbook", "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current"),
    ("GRADE Working Group", "https://www.gradeworkinggroup.org/"),
)

QUESTIONS = (
    "ما السؤال الذي صممت الدراسة للإجابة عنه فعلًا؟", "هل التصميم مناسب للسؤال أم يجيب عن سؤال أضعف؟", "كيف اختير المشاركون ومن لم يدخل الدراسة؟",
    "هل القياسات معرفة مسبقًا وموثوقة وملائمة للسياق؟", "ما مقدار البيانات المفقودة وهل يختلف الغياب بين المجموعات؟", "ما أهم مصدر محتمل للخلط أو التحيز؟",
    "هل التحليل متوافق مع التصميم وبنية البيانات؟", "هل عُرض حجم الأثر مع عدم اليقين؟", "هل النتيجة المهمة عمليًا هي نفسها النتيجة المهمة إحصائيًا؟",
    "هل تبدلت النتائج أو التحليلات بعد رؤية البيانات؟", "هل توجد تحليلات حساسية تدعم الاستنتاج؟", "هل توجد نتائج سلبية أو جانبية لم تحظ بالاهتمام نفسه؟",
    "هل العينة والسياق يشبهان من نريد تطبيق النتيجة عليهم؟", "هل المتابعة طويلة بما يكفي للسؤال؟", "هل توجد دراسات أخرى متسقة أم أن النتيجة منفردة؟",
    "هل للممول أو الباحث تضارب مصالح ذي صلة؟", "هل البروتوكول أو التسجيل متاحان؟", "هل البيانات أو الكود أو المواد متاحة بقدر مناسب؟",
    "ما المعلومة الجديدة التي قد تغير استنتاجي؟", "كيف سأشرح النتيجة بلغة لا تتجاوز ما تسمح به البيانات؟",
)

STYLE = """
:root{--ink:#12383d;--muted:#536f73;--line:#c8e3df;--bg:#f3fbf9;--accent:#6d3150;--blue:#174f7a}*{box-sizing:border-box}body{margin:0;font-family:Tahoma,Arial,sans-serif;line-height:1.9;color:var(--ink);background:linear-gradient(140deg,#fff,var(--bg));direction:rtl}.wrap{width:min(1120px,92%);margin:auto}header,footer{padding:20px 0}.brand{font-weight:900;text-decoration:none;color:var(--ink)}nav a{margin-inline-end:14px}main{padding:22px 0 55px}.crumbs{font-size:.92rem;color:var(--muted)}h1{font-size:clamp(2rem,5vw,3.8rem);line-height:1.25}h2{margin-top:2.2rem}.lead{font-size:1.16rem;max-width:900px}.card,.note{background:#fff;border:1px solid var(--line);border-radius:18px;padding:20px;margin:18px 0}.note{border-inline-start:5px solid var(--accent)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.sources li,.questions li{margin:.55rem 0}a{color:var(--blue)}.tag{display:inline-block;padding:5px 10px;border-radius:999px;background:#e8f5f2;margin:3px;font-size:.88rem}.hub-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.hub-grid article{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px}@media(max-width:850px){.grid,.hub-grid{grid-template-columns:1fr}}@media print{nav,.related{display:none}body{background:#fff}}
"""

def esc(value: str) -> str: return html.escape(value, quote=True)
def words(value: str) -> int: return len(re.findall(r"[\u0600-\u06FFA-Za-z0-9]+", re.sub(r"<[^>]+>", " ", value)))

def page_text(topic: Topic, intent_title: str, intent_desc: str) -> str:
    return f"""
<p class="lead">هذا الدليل يشرح <strong>{esc(intent_title)}</strong> في موضوع <strong>{esc(topic.title)}</strong>. الهدف هو تعلم قراءة الدليل لا حفظ حكم جاهز. {esc(topic.definition)}</p>
<section><h2>لماذا يهم هذا الموضوع؟</h2><p>{esc(topic.value)} عند قراءة أي بحث، افصل بين ثلاثة مستويات: ما الذي لاحظته البيانات، وما الذي يسمح التصميم باستنتاجه، وما الذي يصلح نقله إلى قرار واقعي. الخلط بين هذه المستويات هو أحد أكثر أسباب تضخيم الادعاءات العلمية.</p><p>{esc(intent_desc)} لا تجعل اسم التصميم أو شهرة المجلة بديلًا عن فحص السؤال والعينة والقياس والتحليل والشفافية. الدراسة القوية هي سلسلة قرارات مترابطة؛ ضعف حلقة حاسمة قد يغير معنى النتيجة حتى عندما تبدو الأرقام مقنعة.</p></section>
<section><h2>خريطة قراءة عملية</h2><div class="grid"><div class="card"><h3>1. السؤال قبل النتيجة</h3><p>اكتب السؤال بصيغة واضحة: من هم السكان؟ ما التعرض أو التدخل؟ ما المقارنة؟ ما النتيجة والزمن؟ ثم تحقق أن التحليل النهائي يجيب عن السؤال نفسه لا عن نسخة أسهل منه.</p></div><div class="card"><h3>2. من دخل الدراسة؟</h3><p>افحص طريقة الاختيار ومعايير الإدراج والاستبعاد وحجم العينة والفقد. اسأل من لم يتم تمثيله، لأن قابلية التعميم تبدأ من تركيب العينة لا من الخاتمة.</p></div><div class="card"><h3>3. كيف قيس المتغير؟</h3><p>ابحث عن تعريف تشغيلي واضح وثبات وصدق مناسبين، وتوقيت القياس، وهل كان القياس متساويًا بين المجموعات. القياس الرديء لا يصبح جيدًا بكبر العينة.</p></div><div class="card"><h3>4. هل التحليل يحترم التصميم؟</h3><p>راجع بنية البيانات والعناقيد والتكرار والبيانات المفقودة والافتراضات والتعديلات. التحليل يجب أن يكون نتيجة للسؤال والتصميم، لا أداة للبحث عن نتيجة جذابة.</p></div></div></section>
<section><h2>أهم خطر يجب ألا يضيع</h2><div class="note"><p>{esc(topic.risks)}</p></div><p>لا يكفي أن تسأل هل يوجد تحيز؛ اسأل <em>كيف</em> يمكن أن يغير النتيجة، وفي أي اتجاه، وهل توجد بيانات أو تحليلات حساسية تقلل هذا القلق. هذا يحول التقييم من قائمة شكلية إلى استدلال سببي ومنهجي.</p></section>
<section><h2>مثال تطبيقي</h2><p>{esc(topic.example)} عند تطبيق المثال، دوّن أولًا الادعاء كما كُتب، ثم أعد صياغته بأضيق لغة يسمح بها التصميم. بعد ذلك أضف حجم الأثر وعدم اليقين وأهم قيد. هذه الصياغة الثانية عادة أدق وأكثر فائدة لاتخاذ القرار.</p><p>مثال لصياغة منضبطة: «وجدت الدراسة فرقًا أو ارتباطًا ضمن العينة وفي ظروف القياس المحددة، مع مقدار وعدم يقين موضحين؛ ولا يمكن توسيع الاستنتاج إلى السببية أو كل السكان إلا بقدر ما يسمح التصميم والأدلة المتراكمة». هذه اللغة تمنع القفز من البيانات إلى اليقين.</p></section>
<section><h2>كيف تفسر النتيجة دون تضخيم؟</h2><p>ابدأ بحجم الأثر لا بعلامة الدلالة فقط. افحص فترة عدم اليقين، ثم قارن القيم المعقولة بحدود الأهمية العملية. بعد ذلك ضع خطر التحيز وعدم المباشرة وعدم الاتساق في الحساب. إذا كانت النتيجة دقيقة إحصائيًا لكنها صغيرة وظيفيًا، فقل ذلك. وإذا كانت واعدة لكن غير دقيقة، فقل إن عدم اليقين ما زال واسعًا.</p><p>تجنب عبارات مثل «أثبتت الدراسة» عندما يكون التصميم رصديًا أو العينة صغيرة أو النتيجة استكشافية. استخدم وصفًا متناسبًا: ارتبط، لوحظ، قُدر، خفّض في هذه التجربة، أو ما زال غير مؤكد. قوة اللغة يجب أن تتبع قوة التصميم والدليل المتراكم.</p></section>
<section><h2>أسئلة التقييم الأساسية</h2><ol class="questions">{''.join(f'<li>{esc(q)}</li>' for q in QUESTIONS[:10])}</ol></section>
<section><h2>من الدراسة إلى التطبيق</h2><p>التطبيق ليس نسخ متوسط الدراسة على كل شخص. افحص تشابه السكان والسياق والموارد وشدة المشكلة والقيم والتفضيلات والبدائل والأضرار المحتملة. في الصحة النفسية والتربية الدامجة، أعط وزنًا للنتائج الوظيفية والمشاركة وجودة الحياة، ولا تختزل النجاح إلى تحسن درجة واحدة.</p><p>للمدرسة أو الأسرة أو المختص: حدد قرارًا قابلًا للعكس قدر الإمكان، عرّف ما ستراقبه، حدد مدة مناسبة للمراجعة، وسجل مؤشرات التحسن والضرر معًا. إذا كانت الأدلة منخفضة اليقين، يمكن أن يكون القرار تجريبيًا مراقبًا بدل تقديمه كحل مؤكد.</p></section>
<section><h2>متى نحتاج دليلًا أقوى؟</h2><p>تزداد الحاجة إلى دليل أقوى عندما يكون القرار عالي المخاطر، مكلفًا، طويل الأثر، أو عندما يكون الأثر المتوقع صغيرًا أو النتائج متعارضة. حينها ابحث عن تكرار مستقل، مراجعة منهجية، تسجيل مسبق، قياسات أكثر موثوقية، متابعة أطول، أو تصميم يقلل مصادر التحيز الرئيسية.</p><p>إذا لم تتوفر أدلة قوية، لا تملأ الفراغ باليقين. وصف غياب المعرفة جزء من المعرفة نفسها، ويمكن أن يقود إلى قرار أكثر تحفظًا، تجربة محدودة، أو جمع بيانات محلية أفضل.</p></section>
"""

def sources_html(topic: Topic) -> str:
    seen = set(); items=[]
    for name,url in (*topic.sources,*COMMON_SOURCES):
        if url in seen: continue
        seen.add(url); items.append(f'<li><a href="{esc(url)}" rel="noopener noreferrer">{esc(name)}</a> — مرجع منهجي أو إرشادي أصلي/مؤسسي للمراجعة والتحقق.</li>')
    return '<ul class="sources">'+''.join(items)+'</ul>'

def schema(title: str, canonical: str, description: str, topic: Topic) -> str:
    payload={"@context":"https://schema.org","@graph":[{"@type":["Article","LearningResource"],"headline":title,"name":title,"description":description,"url":canonical,"inLanguage":"ar","isAccessibleForFree":True,"educationalUse":["التعلم","التقييم النقدي"],"about":{"@type":"Thing","name":topic.title},"publisher":{"@type":"Organization","name":"منصة روافد","url":"https://healthrenewal.org/"}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"الرئيسية","item":"https://healthrenewal.org/"},{"@type":"ListItem","position":2,"name":SECTION,"item":BASE},{"@type":"ListItem","position":3,"name":title,"item":canonical}]}]}
    return json.dumps(payload,ensure_ascii=False,separators=(",",":" )).replace("</","<\\/")

def render_page(topic: Topic, intent_slug: str, intent_title: str, intent_desc: str) -> str:
    title=f"{intent_title}: {topic.title}"
    canonical=f"{BASE}{topic.slug}-{intent_slug}/"
    description=f"دليل عربي منهجي حول {intent_title} في {topic.title}: قراءة البحث، التحيز، تفسير النتائج، عدم اليقين والتطبيق العملي مع مصادر موثوقة."
    body=page_text(topic,intent_title,intent_desc)
    related=[]
    for s,t,d in INTENTS:
        if s != intent_slug and len(related)<5: related.append((f"{BASE}{topic.slug}-{s}/",t))
    return f'''<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | منصة روافد</title><meta name="description" content="{esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="{esc(canonical)}"><meta property="og:type" content="article"><meta property="og:locale" content="ar_AR"><meta property="og:site_name" content="منصة روافد"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}"><meta property="og:url" content="{esc(canonical)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{esc(title)}"><meta name="twitter:description" content="{esc(description)}"><script type="application/ld+json">{schema(title,canonical,description,topic)}</script><style>{STYLE}</style></head><body><header class="wrap"><a class="brand" href="https://healthrenewal.org/">منصة روافد</a><nav aria-label="التنقل"><a href="{BASE}">البحث والدليل والتعلم</a><a href="https://healthrenewal.org/library/">المكتبة</a><a href="https://healthrenewal.org/magazine/">الأبحاث</a><a href="https://healthrenewal.org/trust/">المنهجية</a></nav></header><main class="wrap"><p class="crumbs"><a href="https://healthrenewal.org/">الرئيسية</a> / <a href="{BASE}">{SECTION}</a> / {esc(topic.title)}</p><span class="tag">تعلم البحث</span><span class="tag">قراءة الدليل</span><span class="tag">{esc(topic.title)}</span><h1>{esc(title)}</h1>{body}<section><h2>مصادر أساسية للتحقق والتوسع</h2>{sources_html(topic)}<p class="note">هذه الصفحة تعليمية ولا تحول نتائج الدراسات إلى تشخيص فردي أو توصية علاجية شخصية. عند القرارات السريرية أو التعليمية عالية المخاطر يلزم تقييم مهني وسياق كامل.</p></section><section class="related"><h2>تابع المسار</h2><ul>{''.join(f'<li><a href="{u}">{esc(t)} — {esc(topic.title)}</a></li>' for u,t in related)}</ul></section></main><footer class="wrap">منصة روافد · محتوى تعليمي منهجي قابل للمراجعة والتحديث</footer></body></html>'''

def render_hub(pages: list[dict[str,str]]) -> str:
    desc="موسوعة عربية لتعلم قراءة الدراسات وتقييم الدليل: 500 دليل منهجي في تصميم البحث، التحيز، القياس، الإحصاء، المراجعات المنهجية والتطبيق المبني على الدليل."
    groups=[]
    for topic in TOPICS:
        subset=[p for p in pages if p['topic']==topic.slug]
        cards=''.join(f'<article><h3><a href="{esc(p["url"])}">{esc(p["title"])}</a></h3><p>{esc(p["description"])}</p></article>' for p in subset)
        groups.append(f'<section><h2>{esc(topic.title)}</h2><p>{esc(topic.definition)} {esc(topic.value)}</p><div class="hub-grid">{cards}</div></section>')
    itemlist={"@context":"https://schema.org","@type":"CollectionPage","name":SECTION,"description":desc,"url":BASE,"inLanguage":"ar","mainEntity":{"@type":"ItemList","numberOfItems":len(pages),"itemListElement":[{"@type":"ListItem","position":i+1,"name":p['title'],"url":p['url']} for i,p in enumerate(pages)]}}
    return f'''<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{SECTION} | 500 دليل لفهم الدراسات وتقييم الأدلة | منصة روافد</title><meta name="description" content="{esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="{BASE}"><meta property="og:type" content="website"><meta property="og:title" content="{SECTION}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{BASE}"><script type="application/ld+json">{json.dumps(itemlist,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')}</script><style>{STYLE}</style></head><body><header class="wrap"><a class="brand" href="https://healthrenewal.org/">منصة روافد</a><nav><a href="https://healthrenewal.org/library/">المكتبة</a><a href="https://healthrenewal.org/magazine/">الأبحاث</a><a href="https://healthrenewal.org/trust/">المنهجية</a></nav></header><main class="wrap"><p class="crumbs"><a href="https://healthrenewal.org/">الرئيسية</a> / {SECTION}</p><h1>{SECTION}</h1><p class="lead">{esc(desc)}</p><div class="note"><strong>{len(pages)} صفحة تعليمية مستقلة.</strong> التنظيم هنا حسب موضوع البحث ثم نية التعلم، وليس تكرار صفحة واحدة بعناوين مختلفة. كل مسار يربط السؤال بالتصميم والقياس والتحليل والتحيز وعدم اليقين والتطبيق.</div>{''.join(groups)}</main><footer class="wrap">منصة روافد · البحث والدليل والتعلم</footer></body></html>'''

def validate(output: Path, pages: list[dict[str,str]]) -> dict[str,object]:
    files=sorted(output.glob('*/index.html'))
    if len(files)!=500: raise ValueError(f"expected 500 child pages, got {len(files)}")
    if len({p['url'] for p in pages})!=500 or len({p['title'] for p in pages})!=500: raise ValueError("duplicate URL/title")
    hashes=set(); min_words=10**9; failures=[]
    for f in files:
        text=f.read_text(encoding='utf-8'); wc=words(text); min_words=min(min_words,wc)
        visible=re.sub(r"\s+"," ",re.sub(r"<[^>]+>"," ",text)).strip()
        h=hash(visible)
        if h in hashes: failures.append(f"duplicate body {f}")
        hashes.add(h)
        for needle in ('<h1>','rel="canonical"','application/ld+json','name="description"','name="robots"'):
            if needle not in text: failures.append(f"missing {needle}: {f}")
        if wc<650: failures.append(f"thin {wc}: {f}")
    if failures: raise ValueError('; '.join(failures[:20]))
    return {"schemaVersion":VERSION,"status":"passed","childPages":len(files),"hubPages":1,"totalPages":501,"uniqueTitles":500,"uniqueUrls":500,"minimumWordCount":min_words,"duplicateBodies":0,"sourcePolicy":"institutional-primary-methodology-sources","seo":{"canonical":True,"robotsIndexFollow":True,"metaDescription":True,"openGraph":True,"twitter":True,"jsonLd":True,"breadcrumbs":True,"itemList":True}}

def publish(site: Path) -> dict[str,object]:
    output=site/'sections'/'research-evidence-learning'; output.mkdir(parents=True,exist_ok=True)
    pages=[]
    for topic in TOPICS:
        for intent_slug,intent_title,intent_desc in INTENTS:
            slug=f"{topic.slug}-{intent_slug}"; target=output/slug/'index.html'; target.parent.mkdir(parents=True,exist_ok=True)
            target.write_text(render_page(topic,intent_slug,intent_title,intent_desc),encoding='utf-8')
            pages.append({"topic":topic.slug,"slug":slug,"title":f"{intent_title}: {topic.title}","description":f"{intent_title} في {topic.title}: دليل منهجي عربي لقراءة البحث وتقييم الاستنتاج.","url":f"{BASE}{slug}/"})
    (output/'index.html').write_text(render_hub(pages),encoding='utf-8')
    report=validate(output,pages)
    api=site/'api'; api.mkdir(parents=True,exist_ok=True)
    (api/'research-evidence-learning-v1.json').write_text(json.dumps({**report,"sectionUrl":BASE,"topics":len(TOPICS),"intentsPerTopic":len(INTENTS),"pages":pages},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(report,ensure_ascii=False))
    return report

def main() -> int:
    site=Path(sys.argv[1] if len(sys.argv)>1 else '_site')
    publish(site.resolve())
    return 0

if __name__=='__main__': raise SystemExit(main())
