#!/usr/bin/env python3
import argparse,base64,gzip,html,json,re
from pathlib import Path
BASE='https://healthrenewal.org'; MARK='rawafid-wave100-v1'
def e(x): return html.escape(str(x or ''),quote=True)
def wc(s): return len(re.findall(r'[\u0600-\u06FFA-Za-z0-9]+',re.sub(r'<[^>]+>',' ',s)))
def load_data(root):
    raw=''.join(p.read_text().strip() for p in sorted((root/'data/special_needs_wave100').glob('part*.b64')))
    return json.loads(gzip.decompress(base64.b64decode(raw)).decode())
def lens(c):
    c=str(c)
    if 'الضيق المدرسي' in c:return 'مدرسي','يُفهم الضيق المدرسي من خلال التفاعل بين الطالب والبيئة والحواس والعلاقات والمطالب الأكاديمية، لا بوصفه عنادًا أو ضعف دافعية.'
    if 'اللغة' in c or 'DLD' in c:return 'لغوي','تقييم اللغة الجيد يجمع الفهم والتعبير والسرد والمفردات والقراءة والتعرض اللغوي، ولا يعتمد على اختبار واحد أو لغة واحدة.'
    if 'التواصل المعزز' in c or 'AAC' in c:return 'تواصل','AAC منظومة وصول إلى التواصل وليست جهازًا فقط؛ نجاحها يقاس بقدرة الشخص على التعبير والاختيار والسؤال والرفض عبر البيئات.'
    if 'ADHD' in c:return 'تنفيذي','ADHD يُقرأ كنمط نمائي يؤثر في الانتباه والاندفاع والوظائف التنفيذية عبر أكثر من سياق، مع فحص النوم والقلق والتعلم والعوامل الطبية.'
    if 'التوحد' in c:return 'نمائي','التوحد طيف متنوع؛ المطلوب فهم التواصل والحواس والسلوك التكيفي والاحتياجات الوظيفية والتجربة الداخلية بدل اختزال الشخص في سمة واحدة.'
    if 'الحواس' in c:return 'حسي','الاختلافات الحسية تُفسر بحسب أثرها على المشاركة، مع استبعاد الألم والمشكلات الطبية والسمعية والبصرية عند وجود تغير مفاجئ أو ضيق شديد.'
    if 'صعوبات التعلم' in c:return 'تعليمي','صعوبات التعلم تحتاج تحليل المهارة الأساسية وجودة التعليم وخط الأساس والاستجابة لتدخل واضح، لا الاكتفاء بالدرجات أو الانطباع.'
    if 'الصحة النفسية' in c:return 'نفسي','الأعراض النفسية تُفهم بالمدة والشدة والأثر الوظيفي والسلامة، مع التفريق بين المشاعر المتوقعة والحالة التي تستدعي تقييمًا متخصصًا.'
    if 'الحقوق' in c:return 'حقوقي','المنظور الحقوقي يبدأ بالكرامة والاختيار وعدم التمييز وإزالة الحواجز، مع فصل المبادئ الدولية عن القوانين والإجراءات المحلية.'
    if 'الأسرة' in c:return 'أسري','الخطة المستدامة توزع الأدوار وتحمي الشخص والأسرة من الاعتماد على مقدم رعاية واحد وتبني بدائل واضحة للطوارئ والانتقال.'
    return 'عملي','تبدأ الصفحة بوصف وظيفي دقيق، ثم تجمع البيانات وتختار تدخلًا أو تكييفًا قابلًا للقياس وتراجع فائدته بدل اتباع وصفات عامة.'
def answer(q,p,ln):
    return f'الإجابة المختصرة: في موضوع «{p["primary_keyword"]}» لا يكفي عرض واحد أو موقف واحد للحكم. {ln} ابدأ بالسياق والأثر الوظيفي، ثم اجمع خط أساس وحدد خطوة دعم واحدة قابلة للقياس. هذه الصفحة تثقيفية ولا تستبدل التقييم المهني عندما توجد حاجة تشخيصية أو طبية أو خطر على السلامة.'
def prose(p,ln):
    k=e(p['primary_keyword']); axis=e(p['source_axis']); intent=e(p['intent']); audience=e(p['audience'])
    blocks=[
    f'<h2>ما الذي تعنيه الصفحة عمليًا؟</h2><p>موضوع <strong>{k}</strong> لا يحتاج تعريفًا نظريًا فقط. الهدف هو تحويل السؤال إلى قرارات مفيدة للشخص والأسرة والمدرسة أو مقدم الخدمة. {e(ln)} هذا يمنع خطأين شائعين: تحويل المصطلح إلى تشخيص ذاتي، أو القفز مباشرة إلى علاج أو أداة قبل معرفة المشكلة التي نريد حلها.</p><p>نية البحث الأساسية هنا هي {intent}، والجمهور المقصود هو {audience}. لذلك تعرض الصفحة المعلومات على ثلاث طبقات: فهم ما نلاحظه، تحديد ما يحتاج إلى تقييم أو استبعاد، ثم بناء دعم يمكن قياسه ومراجعته. المبدأ الأهم هو أن جودة الخطة تُقاس بالمشاركة والاستقلال والأمان وجودة الحياة، لا بكثرة الجلسات أو صرامة البرنامج.</p>',
    f'<h2>ابدأ بوصف قابل للملاحظة</h2><p>قبل استخدام أي تسمية، اكتب ما يحدث بلغة يمكن لشخصين الاتفاق عليها: متى يبدأ؟ كم يستمر؟ في أي بيئة؟ ما الذي يسبقه؟ ما الذي يخففه؟ وما الذي يتغير بعده؟ في {k} يساعد هذا الوصف على التمييز بين النمط المستمر والموقف العابر، وبين الحاجة الحقيقية إلى دعم وبين اختلاف طبيعي لا يحتاج إلى تصحيح.</p><p>افصل دائمًا بين <strong>الملاحظة</strong> و<strong>التفسير</strong>. الملاحظة قد تكون تأخرًا، تجنبًا، خطأ متكررًا، صعوبة تواصل أو انخفاض مشاركة. أما تفسير السبب فيحتاج معلومات إضافية. هذا الفصل مهم خصوصًا في موضوعات النمو والصحة النفسية والتربية الخاصة، لأن الأعراض المتشابهة قد تنتج عن أسباب مختلفة.</p>',
    f'<h2>خط أساس قبل أي تغيير</h2><p>أنشئ خط أساس بسيطًا لمدة مناسبة: التكرار، المدة، نسبة النجاح، مستوى المساعدة، أو جودة الأداء في مهمة محددة. لا تجعل أسوأ يوم هو المرجع الوحيد. عند التعامل مع {k} يمكن أن تكشف البيانات فروقًا مهمة بين البيت والمدرسة، بين الصباح والمساء، أو بين مهمة مفتوحة وأخرى منظمة.</p><p>الخط الأساس ليس بحثًا أكاديميًا معقدًا. يكفي أن يكون واضحًا وثابتًا وقابلًا للمقارنة. إذا غيرنا عدة عوامل في وقت واحد فلن نعرف ما الذي ساعد. لذلك يفضّل اختيار متغير أو تكييف واحد ثم مراجعة النتيجة في موعد محدد.</p>',
    f'<h2>ما الذي يجب استبعاده أو فحصه؟</h2><p>محور الصفحة هو {axis}. لكن التفكير الدقيق لا ينسب كل صعوبة إلى هذا المحور تلقائيًا. بحسب الحالة قد نحتاج إلى مراجعة السمع أو البصر أو الألم أو النوم أو الأدوية أو اللغة أو القلق أو جودة التعليم أو التغيرات البيئية. ظهور تغير مفاجئ، تراجع سريع، ألم، فقدان مهارة أو خطر على السلامة يرفع أولوية التقييم المهني.</p><p>في المقابل، غياب علامة واحدة لا يستبعد الحاجة إلى الدعم. الناس يختلفون في طريقة التعبير، وبعضهم يعوض أو يخفي الصعوبة في بيئة ثم ينهار في أخرى. لهذا تكون المعلومات من الشخص نفسه ومن الأسرة والمدرسة والمختص أكثر فائدة من الاعتماد على مصدر واحد.</p>',
    f'<h2>خطة دعم قابلة للتنفيذ</h2><ol><li>حدد هدفًا وظيفيًا واحدًا مرتبطًا بـ {k}.</li><li>اختر تكييفًا أو مهارة أو أداة تخدم الهدف مباشرة.</li><li>حدد من سينفذ الخطوة وأين ومتى.</li><li>حافظ على بديل عند تعطل الأداة أو ارتفاع الضيق.</li><li>اجمع نفس المقياس المستخدم في خط الأساس.</li><li>راجع الفائدة والعبء مع الشخص والأسرة.</li><li>عدّل الخطة أو أوقف ما لا يقدم فائدة ذات معنى.</li></ol><p>الخطط الجيدة صغيرة بما يكفي للتنفيذ وواضحة بما يكفي للتقييم. لا قيمة لخطة مثالية على الورق لا يستطيع الفريق تطبيقها باستمرار.</p>',
    f'<h2>كيف نقيس النجاح؟</h2><p>النجاح في {k} يجب أن يعكس نتيجة حقيقية: مشاركة أكبر، استقلال أعلى، تواصل أوضح، أخطاء أقل في مهارة مستهدفة، قدرة أفضل على طلب المساعدة، انخفاض الضيق أو تقليل الوقت اللازم للتعافي. تجنب المؤشرات التي تقيس راحة المحيط فقط، مثل الهدوء الظاهري أو الامتثال، إذا كان الشخص يدفع ثمن ذلك إنهاكًا أو قلقًا.</p><p>اسأل دوريًا: هل تحسن الهدف الذي اتفقنا عليه؟ هل ظهرت آثار جانبية أو عبء غير متوقع؟ هل انتقلت الفائدة إلى بيئة أخرى؟ وهل ما زال الهدف مهمًا للشخص؟ هذه الأسئلة تحمي من استمرار تدخل غير مفيد بسبب العادة أو الشهرة.</p>',
    f'<h2>دور الأسرة والمدرسة والمختص</h2><p><strong>الأسرة:</strong> تقدم التاريخ والسياق وتحدد الأولويات الواقعية، من دون تحويل الحياة اليومية إلى اختبار مستمر. <strong>المدرسة:</strong> تعدّل البيئة والمهمة وطريقة عرض التعليمات والتقييم عند الحاجة، وتوثق الأداء بدل استخدام أوصاف مثل كسول أو غير متعاون. <strong>المختص:</strong> يربط البيانات بالأدلة ويشرح حدود اليقين ويقترح هدفًا قابلًا للمراجعة. <strong>الشخص نفسه:</strong> صوته وراحته واختياره عناصر أساسية في تعريف النجاح.</p>',
    f'<h2>أخطاء شائعة</h2><ul><li>استخدام المصطلح كأنه تفسير كامل لكل السلوك.</li><li>التشخيص الذاتي من قائمة قصيرة أو اختبار إنترنت.</li><li>بدء علاج أو شراء جهاز قبل تحديد الهدف.</li><li>تجاهل النوم والألم واللغة والحواس والبيئة.</li><li>قياس الجلسة بدل الحياة اليومية.</li><li>تغيير أشياء كثيرة معًا ثم فقدان القدرة على معرفة ما نجح.</li><li>نسخ خطة طفل أو طالب آخر دون مراعاة الفروق الفردية.</li><li>إهمال المراجعة الدورية لأن التدخل مشهور أو مكلف.</li></ul>',
    f'<h2>متى يصبح التقييم المتخصص مهمًا؟</h2><p>اطلب تقييمًا مهنيًا عندما تؤثر الصعوبة المرتبطة بـ {k} بصورة مستمرة في التعلم أو التواصل أو العلاقات أو العناية بالنفس أو الأمان، أو عندما يفشل الدعم الأولي رغم تطبيقه بوضوح. كما يلزم تصعيد أسرع عند وجود فقدان مهارة، أعراض عصبية جديدة، ألم، تدهور شديد في النوم أو الأكل، إيذاء للنفس أو الآخرين، أو أي علامة طبية مقلقة.</p><p>التقييم الجيد لا يهدف فقط إلى وضع اسم؛ بل إلى تفسير الاحتياجات، تحديد نقاط القوة، استبعاد البدائل، ووضع توصيات قابلة للتطبيق في البيئة الفعلية.</p>',
    f'<h2>كيف تستخدم هذه الصفحة مع فريق الدعم؟</h2><p>حوّل المعلومات إلى ورقة عمل قصيرة: اكتب السؤال الأساسي، ثلاث ملاحظات موثقة، خط الأساس، العوامل التي قد تفسر النمط، التكييف المقترح، المسؤول عن التنفيذ، ومؤشر النجاح. بعد فترة محددة اجتمع الفريق لمراجعة البيانات بدل الدفاع عن الانطباعات. هذا الأسلوب يجعل موضوع {k} جزءًا من عملية قرار مشتركة لا مصدرًا للوم أو الوصم.</p>'
    ]
    return ''.join(blocks)
def render_topic(p,siblings):
    kind,ln=lens(p['cluster']); url=f'{BASE}/special-needs/knowledge/{p["slug"]}/'; desc=f'دليل عربي موثق حول {p["primary_keyword"]}: فهم عملي، تقييم، دعم، قياس، أسئلة بحث ومراجع موثوقة.'
    qs=list(dict.fromkeys((p.get('questions') or [])+[f'ما أهم ما يجب معرفته عن {p["primary_keyword"]}؟',f'متى أحتاج إلى تقييم متخصص في {p["primary_keyword"]}؟',f'كيف أقيس نجاح الدعم في {p["primary_keyword"]}؟']))[:8]
    faq=[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':answer(q,p,ln)}} for q in qs]
    schema={'@context':'https://schema.org','@graph':[{'@type':'Article','headline':p['title'],'description':desc,'inLanguage':'ar','mainEntityOfPage':url,'about':p['source_axis'],'author':{'@type':'Organization','name':'روافد'}},{'@type':'FAQPage','mainEntity':faq},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'روافد','item':BASE+'/'},{'@type':'ListItem','position':2,'name':'الاحتياجات الخاصة','item':BASE+'/special-needs/'},{'@type':'ListItem','position':3,'name':p['title'],'item':url}]}]}
    refs=''.join(f'<li><a href="{e(s["url"])}" rel="noopener noreferrer">{e(s.get("name") or s["url"])}</a> <small>{e(s.get("tier"))}</small></li>' for s in p.get('sources',[]))
    rel=''.join(f'<li><a href="../{e(x["slug"])}/">{e(x["title"])}</a></li>' for x in siblings[:6])
    fq=''.join(f'<details><summary>{e(q)}</summary><p>{e(answer(q,p,ln))}</p></details>' for q in qs)
    return f'''<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(p['title'])} | روافد</title><meta name="description" content="{e(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{url}"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><style>body{{margin:0;background:#f6faf9;color:#173f43;font-family:Tahoma,Arial,sans-serif;line-height:1.95}}header,main{{width:min(980px,92%);margin:auto}}header{{padding:42px 0 20px}}article{{background:#fff;border:1px solid #d7e7e4;border-radius:18px;padding:clamp(18px,4vw,38px)}}h1{{font-size:clamp(2rem,5vw,3.2rem);line-height:1.35}}h2{{color:#74304e;margin-top:2rem}}a{{color:#066b64}}.note{{background:#fff8e9;border-right:5px solid #9a6310;padding:14px}}details{{border-top:1px solid #dbe8e6;padding:12px 0}}summary{{font-weight:800}}small{{color:#657b7d}}</style></head><body><!-- {MARK} --><header><a href="/special-needs/">الاحتياجات الخاصة</a> ← <a href="/special-needs/knowledge/">مكتبة المعرفة</a><h1>{e(p['title'])}</h1><p>{e(desc)}</p><p><strong>المحور:</strong> {e(p['cluster'])} · <strong>نية البحث:</strong> {e(p['intent'])} · <strong>مراجعة:</strong> أغسطس 2026</p></header><main><article><p class="note"><strong>حدود المحتوى:</strong> تثقيفي وغير تشخيصي. لا يقدم جرعات دوائية أو وعود علاجية. عند الخطر أو الطوارئ تُتبع الخدمات المحلية.</p>{prose(p,ln)}<h2>أسئلة تحاكي نية البحث</h2>{fq}<h2>المراجع الأساسية</h2><p>تُستخدم المصادر الأصلية والمؤسسية للتحقق من المفاهيم والحدود. الرابط لا يعني أن الجهة تصادق على كل صياغة في الصفحة.</p><ul>{refs}</ul><h2>صفحات مرتبطة</h2><ul>{rel}</ul><p>آخر مراجعة تحريرية: أغسطس 2026. تُراجع الصفحة عند ظهور دليل مؤثر أو تحديث إرشادي.</p></article></main></body></html>'''
def render_hub(p,children):
    url=f'{BASE}/special-needs/knowledge/{p["slug"]}/'; cards=''.join(f'<article><h2><a href="../{e(x["slug"])}/">{e(x["title"])}</a></h2><p>{e(x["rationale"])}</p></article>' for x in children)
    return f'''<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(p['title'])} | روافد</title><meta name="description" content="خريطة مرجعية لموضوع {e(p['primary_keyword'])}."><meta name="robots" content="index,follow"><link rel="canonical" href="{url}"></head><body><!-- {MARK} --><main><h1>{e(p['title'])}</h1><p>هذه خريطة موضوعية تربط الصفحات المستقلة حسب نية البحث وتمنع تكرار المحتوى. ابدأ بالسؤال الأقرب إلى حاجتك ثم انتقل إلى الروابط الداخلية.</p>{cards}</main></body></html>'''
def main():
    ap=argparse.ArgumentParser();ap.add_argument('site',nargs='?',default='_site');ap.add_argument('--repo-root',default='.');a=ap.parse_args();site=Path(a.site);root=Path(a.repo_root);data=load_data(root);pages=data['pages'];assert len(pages)==100 and len({p['slug'] for p in pages})==100
    out=site/'special-needs'/'knowledge';out.mkdir(parents=True,exist_ok=True);counts=[];conf=[]
    for p in pages:
        d=out/p['slug']/'index.html';d.parent.mkdir(parents=True,exist_ok=True)
        if d.exists() and MARK not in d.read_text(encoding='utf-8',errors='replace'):conf.append(str(d));continue
        if p['content_type']=='hub':s=render_hub(p,[x for x in pages if x['content_type']!='hub' and x['cluster']==p['cluster']])
        else:s=render_topic(p,[x for x in pages if x['content_type']!='hub' and x['cluster']==p['cluster'] and x['slug']!=p['slug']])
        d.write_text(s,encoding='utf-8',newline='\n');counts.append((p['slug'],wc(s),p['content_type']))
    hubs=[x for x in pages if x['content_type']=='hub']; links=''.join(f'<li><a href="{e(x["slug"])}/">{e(x["title"])}</a></li>' for x in hubs)
    (out/'index.html').write_text(f'<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="robots" content="index,follow"><link rel="canonical" href="{BASE}/special-needs/knowledge/"><title>مكتبة روافد للاحتياجات الخاصة</title></head><body><!-- {MARK} --><main><h1>مكتبة روافد للاحتياجات الخاصة والتربية الدامجة</h1><p>100 صفحة منتقاة من فجوات البحث العربية ومكتبة روافد التحريرية، مع مراجع وروابط داخلية ومنع التكرار.</p><ul>{links}</ul></main></body></html>',encoding='utf-8')
    topic=[n for _,n,t in counts if t!='hub'];bad=[{'slug':s,'words':n,'type':t} for s,n,t in counts if t!='hub' and n<1200]
    rep={'schemaVersion':1,'status':'passed' if len(counts)==100 and not conf and not bad else 'failed','expected':100,'generated':len(counts),'topicPages':90,'hubPages':10,'minimumTopicWords':min(topic) if topic else 0,'conflicts':conf,'qualityFailures':bad,'marker':MARK}
    api=site/'api';api.mkdir(parents=True,exist_ok=True);(api/'special-needs-wave100-v1.json').write_text(json.dumps(rep,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps(rep,ensure_ascii=False));raise SystemExit(0 if rep['status']=='passed' else 1)
if __name__=='__main__':main()
