#!/usr/bin/env python3
"""Compatibility entry point for the magazine production pipeline.

Historical build jobs still call ``publish_magazine_v201.py``. The authoritative
implementation is now the recursive, evidence-first v202 bundle. This wrapper
keeps the old report filename and key names so unrelated pipelines do not break,
while all published magazine output is generated by v202.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from publish_magazine_bundle_v202 import FEED_LIMIT, publish as publish_v202

CONTRACT = 316
TARGET_ARTICLES = 500
BASE = "https://healthrenewal.org"
URL = BASE + "/magazine/"


def publish(site: Path) -> dict[str, Any]:
    site = site.resolve()
    report202 = publish_v202(site)
    published = int(report202.get("published_study_pages") or 0)
    validation = report202.get("validation") or {}
    sitemap = report202.get("sitemap") or {}
    legacy = {
        "version": CONTRACT,
        "publisher_contract": 202,
        "compatibility_mode": "v201-entrypoint-v202-output",
        "canonical_origin": BASE,
        "legacy_origins_remaining": 0,
        "page": "magazine/index.html",
        "url": URL,
        "methodology_published": True,
        "research_summaries_published": published,
        "target_research_summaries": TARGET_ARTICLES,
        "remaining_to_target": max(0, TARGET_ARTICLES - published),
        "unwired_research_pages": int(report202.get("unwired_research_pages") or 0),
        "missing_source_pages": int(report202.get("missing_source_pages") or 0),
        "structurally_complete_pages": int(report202.get("structurally_complete_pages") or 0),
        "bibliographically_verified_and_complete": int(report202.get("bibliographically_verified_and_complete") or 0),
        "rss_contract": "latest-twenty-sorted-by-datePublished",
        "robots": {
            "rss_items": int(report202.get("rss_items") or 0),
            "noindex_pages": int(validation.get("noindex_pages") or 0),
        },
        "sitemap": sitemap,
        "articles": [
            str(item.get("relative_path") or item.get("source_path") or "")
            for item in (report202.get("articles") or [])
            if isinstance(item, dict)
        ],
        "v202_report": "api/magazine-v202.json",
        "bibliography_report": "api/magazine-bibliography-verification-v202.json",
        "source_manifest": "api/magazine-source-manifest-v202.json",
    }
    api = site / "api"
    api.mkdir(parents=True, exist_ok=True)
    (api / "magazine-v201.json").write_text(
        json.dumps(legacy, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps({key: value for key, value in legacy.items() if key != "articles"}, ensure_ascii=False, indent=2))
    return legacy


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("site", nargs="?", default="_site", type=Path)
    args = parser.parse_args()
    publish(args.site)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
