"""Curated Arabic topic inventory for the Quick Information section.

Titles are intentionally direct and curiosity-driven without misleading claims.
The pages generated from this inventory are educational and non-diagnostic.
"""

TOPICS = [
    # 001-035: direct comparisons
    ("sadness-or-depression", "حزن أم اكتئاب؟ 7 فروق لا ينبغي تجاهلها", "comparison", "مقارنات"),
    ("fatigue-or-laziness", "إرهاق أم كسل؟ ما الذي يحدث فعلًا؟", "comparison", "مقارنات"),
    ("normal-anxiety-or-disorder", "قلق طبيعي أم اضطراب قلق؟ متى يتجاوز الحد؟", "comparison", "مقارنات"),
    ("stress-or-burnout", "ضغط نفسي أم احتراق نفسي؟ الفرق الذي يغيّر طريقة التعامل", "comparison", "مقارنات"),
    ("shyness-or-social-anxiety", "خجل أم قلق اجتماعي؟ لا تخلط بينهما", "comparison", "مقارنات"),
    ("introversion-or-isolation", "انطواء أم عزلة؟ متى يصبح الابتعاد مؤلمًا؟", "comparison", "مقارنات"),
    ("love-or-attachment", "حب أم تعلق؟ 6 إشارات تكشف الفرق", "comparison", "مقارنات"),
    ("admiration-or-love", "إعجاب أم حب؟ ما الذي يبقى بعد الحماس الأول؟", "comparison", "مقارنات"),
    ("jealousy-or-control", "غيرة طبيعية أم سيطرة؟ الخط الفاصل بين الاهتمام والأذى", "comparison", "مقارنات"),
    ("conflict-or-harmful-relationship", "خلاف عابر أم علاقة مؤذية؟ راقب النمط لا الحادثة", "comparison", "مقارنات"),
    ("care-or-monitoring", "اهتمام أم مراقبة؟ متى يتحول السؤال إلى انتهاك؟", "comparison", "مقارنات"),
    ("grief-or-depression", "حزن الفقد أم اكتئاب؟ كيف تلاحظ الفرق دون تشخيص ذاتي", "comparison", "مقارنات"),
    ("insomnia-or-short-sleep", "أرق أم قلة نوم؟ المشكلة ليست في عدد الساعات فقط", "comparison", "مقارنات"),
    ("physical-or-mental-exhaustion", "تعب جسدي أم إنهاك نفسي؟ 5 دلائل تساعدك", "comparison", "مقارنات"),
    ("forgetfulness-or-poor-focus", "نسيان طبيعي أم مشكلة تركيز؟ متى يستحق الانتباه؟", "comparison", "مقارنات"),
    ("distraction-or-adhd", "تشتت أم ADHD؟ التشابه لا يعني التشخيص", "comparison", "مقارنات"),
    ("habit-or-addiction", "عادة أم إدمان؟ الاختبار الحقيقي هو فقدان السيطرة", "comparison", "مقارنات"),
    ("phone-use-or-digital-addiction", "استخدام هاتف أم إدمان رقمي؟ راقب الأثر لا الوقت وحده", "comparison", "مقارنات"),
    ("fear-or-panic", "خوف طبيعي أم نوبة هلع؟ ماذا يحدث في الدقائق الأولى؟", "comparison", "مقارنات"),
    ("intrusive-thought-or-ocd", "وسواس عابر أم وسواس قهري؟ الفرق في التكرار والطقوس", "comparison", "مقارنات"),
    ("mood-change-or-bipolar", "تقلب مزاج أم اضطراب ثنائي القطب؟ لا تختصر التشخيص في المزاج", "comparison", "مقارنات"),
    ("irritability-or-anxiety", "عصبية أم قلق؟ أحيانًا يظهر الخوف على شكل غضب", "comparison", "مقارنات"),
    ("hunger-or-emotional-eating", "جوع أم أكل عاطفي؟ اسأل نفسك هذه الأسئلة قبل الأكل", "comparison", "مقارنات"),
    ("laziness-or-procrastination", "كسل أم تسويف؟ لماذا تعرف ما يجب فعله ولا تبدأ؟", "comparison", "مقارنات"),
    ("rest-or-avoidance", "راحة أم هروب؟ متى يصبح التوقف وسيلة لتجنب الحياة؟", "comparison", "مقارنات"),
    ("confidence-or-narcissism", "ثقة بالنفس أم نرجسية؟ الفرق ليس في حب الذات", "comparison", "مقارنات"),
    ("empathy-or-people-pleasing", "تعاطف أم إرضاء للآخرين؟ متى تختفي احتياجاتك؟", "comparison", "مقارنات"),
    ("support-or-rescuing", "دعم أم إنقاذ مفرط؟ المساعدة التي تستنزف الطرفين", "comparison", "مقارنات"),
    ("boundaries-or-cruelty", "حدود صحية أم قسوة؟ كيف تقول لا دون إيذاء؟", "comparison", "مقارنات"),
    ("longing-or-painful-attachment", "اشتياق أم تعلق مؤلم؟ لماذا لا تستطيع التوقف عن التفكير؟", "comparison", "مقارنات"),
    ("caution-or-hypervigilance", "حذر أم فرط يقظة؟ عندما يبقى جسمك مستعدًا للخطر", "comparison", "مقارنات"),
    ("bad-memory-or-stress", "ذاكرة سيئة أم ضغط نفسي؟ كيف يسرق التوتر تركيزك؟", "comparison", "مقارنات"),
    ("self-love-or-selfishness", "حب الذات أم أنانية؟ الحدود التي لا يشرحها الناس", "comparison", "مقارنات"),
    ("loneliness-or-solitude", "وحدة أم احتياج للهدوء؟ الفرق يظهر بعد انتهاء العزلة", "comparison", "مقارنات"),
    ("silence-or-emotional-withdrawal", "صمت أم انسحاب عاطفي؟ متى يصبح السكوت عقابًا؟", "comparison", "مقارنات"),

    # 036-060: educational self-checks
    ("simple-mental-health-check", "اختبار الصحة النفسية البسيط: 10 أسئلة لمراجعة حالتك", "check", "فحوص توعوية"),
    ("do-you-have-insomnia", "هل تعاني من أرق؟ فحص توعوي لا يستبدل التشخيص", "check", "فحوص توعوية"),
    ("does-anxiety-control-your-day", "هل القلق يسيطر على يومك؟ راقب هذه الإشارات", "check", "فحوص توعوية"),
    ("are-you-in-toxic-relationship", "هل أنت في علاقة سامة؟ افحص السلوك لا اللقب", "check", "فحوص توعوية"),
    ("do-you-miss-person-or-idea", "هل تشتاق لشخص أم لفكرة عنه؟ 9 أسئلة صريحة", "check", "فحوص توعوية"),
    ("do-you-need-mental-break", "هل تحتاج إلى استراحة نفسية؟ علامات لا تعالجها القهوة", "check", "فحوص توعوية"),
    ("are-you-emotionally-exhausted", "هل أنت مرهق عاطفيًا؟ اختبر أثر الاستنزاف على يومك", "check", "فحوص توعوية"),
    ("is-phone-stealing-your-sleep", "هل هاتفك يسرق نومك؟ افحص عادات آخر ساعة", "check", "فحوص توعوية"),
    ("are-you-overthinking-life", "هل تفكر أكثر مما تعيش؟ علامات الاجترار الذهني", "check", "فحوص توعوية"),
    ("do-you-fear-people-opinion", "هل تخاف من رأي الناس؟ فحص سريع للخوف من التقييم", "check", "فحوص توعوية"),
    ("do-you-say-yes-while-wanting-no", "هل تقول نعم وأنت تريد الرفض؟ افحص حدودك", "check", "فحوص توعوية"),
    ("is-relationship-draining-you", "هل علاقتك تستنزفك؟ 10 أسئلة قبل تجاهل الإشارات", "check", "فحوص توعوية"),
    ("are-you-stuck-after-breakup", "هل أنت عالق بعد الانفصال؟ راقب ما يبقيك في الماضي", "check", "فحوص توعوية"),
    ("do-you-avoid-people-from-anxiety", "هل تتجنب الناس بسبب القلق؟ فحص للأثر الوظيفي", "check", "فحوص توعوية"),
    ("low-mood-two-weeks", "هل مزاجك منخفض منذ أسبوعين؟ متى تطلب تقييمًا؟", "check", "فحوص توعوية"),
    ("do-you-monitor-partner", "هل تراقب شريكك باستمرار؟ ما وراء الحاجة إلى التأكد", "check", "فحوص توعوية"),
    ("lonely-among-people", "هل تشعر بالوحدة وسط الناس؟ افحص جودة الاتصال لا عدده", "check", "فحوص توعوية"),
    ("is-procrastination-blocking-life", "هل التسويف يعطل حياتك؟ 8 أسئلة تكشف النمط", "check", "فحوص توعوية"),
    ("does-anger-hide-exhaustion", "هل غضبك يخفي تعبًا نفسيًا؟ راقب ما يسبق الانفجار", "check", "فحوص توعوية"),
    ("child-anxiety-or-phase", "هل طفلك قلق أم يمر بمرحلة؟ مؤشرات تحتاج متابعة", "check", "فحوص توعوية"),
    ("teen-needs-support", "هل ابنك المراهق يحتاج دعمًا؟ علامات تتطلب إنصاتًا", "check", "فحوص توعوية"),
    ("distraction-needs-evaluation", "هل تشتتك طبيعي أم يحتاج تقييمًا؟ لا تعتمد على فيديو قصير", "check", "فحوص توعوية"),
    ("burnout-signs-check", "هل لديك علامات احتراق وظيفي؟ فحص واقعي للعمل والطاقة", "check", "فحوص توعوية"),
    ("is-your-sleep-insufficient", "هل نومك غير كافٍ؟ افحص الجودة والتوقيت والأثر", "check", "فحوص توعوية"),
    ("is-your-relationship-psychologically-safe", "هل علاقتك آمنة نفسيًا؟ 10 أسئلة عن الاحترام والخوف", "check", "فحوص توعوية"),

    # 061-090: five-factor pages
    ("five-psychological-causes-of-fatigue", "5 أسباب نفسية قد تجعلك متعبًا طوال الوقت", "five", "أسباب وعلامات"),
    ("five-external-factors-raise-anxiety", "5 عوامل خارجية ترفع القلق دون أن تنتبه", "five", "أسباب وعلامات"),
    ("five-reasons-thinking-of-ex", "5 أسباب تجعلك تفكر بشخص قديم", "five", "أسباب وعلامات"),
    ("five-signs-stress-in-body", "5 علامات أن الضغط النفسي وصل إلى جسدك", "five", "أسباب وعلامات"),
    ("five-reasons-waking-at-night", "5 أسباب محتملة للاستيقاظ في منتصف الليل", "five", "أسباب وعلامات"),
    ("five-habits-worsen-insomnia", "5 عادات مسائية تزيد الأرق", "five", "أسباب وعلامات"),
    ("five-reasons-feeling-empty", "5 أسباب محتملة للشعور بالفراغ", "five", "أسباب وعلامات"),
    ("five-signs-you-need-boundaries", "5 علامات أنك تحتاج إلى حدود أوضح", "five", "أسباب وعلامات"),
    ("five-reasons-fear-rejection", "5 أسباب نفسية قد تجعلك تخاف الرفض", "five", "أسباب وعلامات"),
    ("five-signs-painful-attachment", "5 علامات على تعلق عاطفي مؤلم", "five", "أسباب وعلامات"),
    ("five-reasons-procrastination", "5 أسباب للتسويف لا علاقة لها بالكسل", "five", "أسباب وعلامات"),
    ("five-signs-burnout", "5 علامات أن الإرهاق تحول إلى احتراق نفسي", "five", "أسباب وعلامات"),
    ("five-reasons-sudden-irritability", "5 أسباب محتملة للعصبية المفاجئة", "five", "أسباب وعلامات"),
    ("five-factors-weaken-focus", "5 عوامل تضعف التركيز حتى لدى الأذكياء", "five", "أسباب وعلامات"),
    ("five-reasons-social-withdrawal", "5 أسباب تجعلك تنسحب من الناس", "five", "أسباب وعلامات"),
    ("five-signs-unbalanced-relationship", "5 علامات أن علاقتك غير متوازنة", "five", "أسباب وعلامات"),
    ("five-reasons-excessive-jealousy", "5 أسباب وراء الغيرة الزائدة", "five", "أسباب وعلامات"),
    ("five-signs-people-pleasing", "5 علامات أنك ترضي الجميع على حساب نفسك", "five", "أسباب وعلامات"),
    ("five-reasons-waking-tired", "5 أسباب تجعلك تستيقظ متعبًا رغم النوم", "five", "أسباب وعلامات"),
    ("five-psychological-factors-appetite", "5 عوامل نفسية قد تؤثر على الشهية", "five", "أسباب وعلامات"),
    ("five-reasons-emotional-eating", "5 أسباب للأكل العاطفي وكيف تلاحظها", "five", "أسباب وعلامات"),
    ("five-signs-carrying-others", "5 علامات أنك تحمل مسؤوليات الآخرين", "five", "أسباب وعلامات"),
    ("five-reasons-breakup-hurts", "5 أسباب تجعل الانفصال مؤلمًا حتى عندما كان ضروريًا", "five", "أسباب وعلامات"),
    ("five-signs-not-healed", "5 علامات أنك لم تتعاف بعد من العلاقة", "five", "أسباب وعلامات"),
    ("five-reasons-fear-confrontation", "5 أسباب تجعلك تخاف من المواجهة", "five", "أسباب وعلامات"),
    ("five-habits-destroy-calm", "5 عادات يومية تقتل راحتك النفسية", "five", "أسباب وعلامات"),
    ("five-signs-self-criticism", "5 علامات أنك تقسو على نفسك", "five", "أسباب وعلامات"),
    ("five-reasons-work-drains-you", "5 أسباب تجعل العمل يستنزفك نفسيًا", "five", "أسباب وعلامات"),
    ("five-factors-child-mood", "5 عوامل تؤثر على مزاج الطفل", "five", "أسباب وعلامات"),
    ("five-signs-teen-needs-listening", "5 علامات أن المراهق يحتاج إلى إنصات لا محاضرة", "five", "أسباب وعلامات"),

    # 091-120: relationships and recovery
    ("five-tips-after-breakup", "5 نصائح بعد الانفصال تساعدك دون إنكار الألم", "relationship", "العلاقات والتعافي"),
    ("stop-texting-uninterested-person", "كيف تتوقف عن مراسلة شخص لا يبادلك الاهتمام؟", "relationship", "العلاقات والتعافي"),
    ("when-someone-ghosts-you", "ماذا تفعل عندما يختفي شخص فجأة؟", "relationship", "العلاقات والتعافي"),
    ("set-boundaries-without-guilt", "كيف تضع حدودًا دون شعور بالذنب؟", "relationship", "العلاقات والتعافي"),
    ("deal-with-emotional-neglect", "كيف تتعامل مع التجاهل العاطفي؟", "relationship", "العلاقات والتعافي"),
    ("why-miss-someone-who-hurt-you", "لماذا نشتاق لمن آذانا؟", "relationship", "العلاقات والتعافي"),
    ("how-to-know-real-apology", "كيف تعرف أن الاعتذار حقيقي؟", "relationship", "العلاقات والتعافي"),
    ("when-jealousy-becomes-harmful", "متى تصبح الغيرة مؤذية؟", "relationship", "العلاقات والتعافي"),
    ("leave-draining-relationship-safely", "كيف تخرج من علاقة تستنزفك بأمان؟", "relationship", "العلاقات والتعافي"),
    ("why-return-to-same-relationship", "لماذا تعود إلى العلاقة نفسها؟", "relationship", "العلاقات والتعافي"),
    ("deal-with-inconsistent-person", "كيف تتعامل مع شخص متقلب؟", "relationship", "العلاقات والتعافي"),
    ("is-silent-treatment-abuse", "هل الصمت العقابي إساءة؟", "relationship", "العلاقات والتعافي"),
    ("love-or-possession", "كيف تفرق بين الحب والتملك؟", "relationship", "العلاقات والتعافي"),
    ("fear-loneliness-after-breakup", "لماذا تخاف من الوحدة بعد الانفصال؟", "relationship", "العلاقات والتعافي"),
    ("stop-checking-ex-social-media", "كيف تمنع نفسك من مراقبة حساباته؟", "relationship", "العلاقات والتعافي"),
    ("when-no-closure", "ماذا تفعل عندما لا تحصل على إغلاق للعلاقة؟", "relationship", "العلاقات والتعافي"),
    ("rebuild-trust-after-betrayal", "كيف تستعيد ثقتك بنفسك بعد الخيانة؟", "relationship", "العلاقات والتعافي"),
    ("deal-with-emotional-manipulation", "كيف تتعامل مع التلاعب العاطفي؟", "relationship", "العلاقات والتعافي"),
    ("can-long-distance-work", "هل العلاقة البعيدة قابلة للاستمرار؟", "relationship", "العلاقات والتعافي"),
    ("when-to-stop-trying", "متى يجب أن تتوقف عن المحاولة في العلاقة؟", "relationship", "العلاقات والتعافي"),
    ("say-no-without-long-explanation", "كيف تقول لا دون شرح طويل؟", "relationship", "العلاقات والتعافي"),
    ("deal-with-constant-criticism", "كيف تتعامل مع النقد المستمر؟", "relationship", "العلاقات والتعافي"),
    ("attracted-to-unavailable-person", "لماذا تنجذب إلى شخص غير متاح عاطفيًا؟", "relationship", "العلاقات والتعافي"),
    ("protect-from-emotional-drain", "كيف تحمي نفسك من الاستنزاف العاطفي؟", "relationship", "العلاقات والتعافي"),
    ("relationship-reduces-self-worth", "ماذا تفعل عندما تقلل العلاقة من قيمتك؟", "relationship", "العلاقات والتعافي"),
    ("build-safe-relationship-after-harm", "كيف تبني علاقة آمنة بعد تجربة مؤذية؟", "relationship", "العلاقات والتعافي"),
    ("love-someone-and-leave", "هل يمكن أن تحب شخصًا وتبتعد عنه؟", "relationship", "العلاقات والتعافي"),
    ("deal-with-nostalgia-after-breakup", "كيف تتعامل مع الحنين بعد الانفصال؟", "relationship", "العلاقات والتعافي"),
    ("communicate-needs-clearly", "كيف تتحدث عن احتياجاتك بوضوح؟", "relationship", "العلاقات والتعافي"),
    ("healthy-distance-in-relationship", "متى تكون المسافة في العلاقة صحية؟", "relationship", "العلاقات والتعافي"),

    # 121-140: sleep, stress and digital habits
    ("sleep-when-mind-wont-stop", "كيف تنام عندما لا يتوقف عقلك؟", "habit", "النوم والعادات"),
    ("why-wake-at-three-am", "لماذا تستيقظ في الثالثة صباحًا؟", "habit", "النوم والعادات"),
    ("after-night-without-sleep", "ماذا تفعل بعد ليلة بلا نوم؟", "habit", "النوم والعادات"),
    ("does-nap-fix-sleep-loss", "هل القيلولة تعالج قلة النوم؟", "habit", "النوم والعادات"),
    ("caffeine-and-anxiety", "كيف يؤثر الكافيين على القلق؟", "habit", "النوم والعادات"),
    ("why-phone-increases-stress", "لماذا يزيد الهاتف التوتر؟", "habit", "النوم والعادات"),
    ("stop-thinking-before-sleep", "كيف توقف التفكير قبل النوم؟", "habit", "النوم والعادات"),
    ("does-deep-breathing-reduce-anxiety", "هل التنفس العميق يخفف القلق؟", "habit", "النوم والعادات"),
    ("tired-despite-sleep", "لماذا تشعر بالتعب رغم النوم؟", "habit", "النوم والعادات"),
    ("restore-focus-after-stress", "كيف تستعيد تركيزك بعد الضغط؟", "habit", "النوم والعادات"),
    ("what-stress-does-to-body", "ماذا يحدث لجسمك عند التوتر؟", "habit", "النوم والعادات"),
    ("start-day-without-anxiety", "كيف تبدأ يومك دون أن يقودك القلق؟", "habit", "النوم والعادات"),
    ("does-exercise-help-mood", "هل الرياضة تساعد المزاج؟ ما الذي تقوله الأدلة؟", "habit", "النوم والعادات"),
    ("reduce-news-anxiety", "كيف تقلل قلق الأخبار دون الانفصال عن الواقع؟", "habit", "النوم والعادات"),
    ("when-gaming-becomes-problem", "متى تصبح الألعاب الإلكترونية مشكلة؟", "habit", "النوم والعادات"),
    ("break-phone-checking-habit", "كيف تكسر عادة التحقق من الهاتف؟", "habit", "النوم والعادات"),
    ("why-open-phone-without-reason", "لماذا تفتح الهاتف دون سبب؟", "habit", "النوم والعادات"),
    ("realistic-sleep-routine", "كيف تصنع روتين نوم واقعيًا؟", "habit", "النوم والعادات"),
    ("does-music-help-sleep", "هل الموسيقى تساعد على النوم؟", "habit", "النوم والعادات"),
    ("deal-with-recurring-nightmare", "كيف تتعامل مع كابوس متكرر؟", "habit", "النوم والعادات"),

    # 141-150: family, neurodiversity and addiction
    ("stubborn-child-or-sensory-exhaustion", "هل طفلك عنيد أم مرهق حسيًا؟", "family", "الأسرة والنمو"),
    ("tantrum-or-sensory-meltdown", "نوبة غضب أم انهيار حسي؟", "family", "الأسرة والنمو"),
    ("child-distraction-or-adhd", "تشتت الطفل أم ADHD؟ متى نطلب تقييمًا؟", "family", "الأسرة والنمو"),
    ("speech-delay-or-needs-evaluation", "تأخر كلام أم اختلاف يحتاج تقييمًا؟", "family", "الأسرة والنمو"),
    ("support-anxious-child", "كيف تدعم طفلًا قلقًا دون تعزيز الخوف؟", "family", "الأسرة والنمو"),
    ("talk-to-depressed-teen", "كيف تتحدث مع مراهق مكتئب؟", "family", "الأسرة والنمو"),
    ("help-relapsing-person-without-rescuing", "كيف تساعد شخصًا ينتكس دون أن تنقذه من كل نتيجة؟", "family", "الأسرة والنمو"),
    ("when-habit-becomes-addiction", "متى تتحول العادة إلى إدمان؟", "family", "الأسرة والنمو"),
    ("protect-family-from-addiction-effects", "كيف تحمي الأسرة من آثار الإدمان؟", "family", "الأسرة والنمو"),
    ("caregiver-needs-support", "هل مقدم الرعاية يحتاج دعمًا؟ علامات الإنهاك الصامت", "family", "الأسرة والنمو"),
]

assert len(TOPICS) == 150, len(TOPICS)
assert len({row[0] for row in TOPICS}) == 150
assert len({row[1] for row in TOPICS}) == 150
